defmodule ShuttleWeb.ProjectsControllerTest do
  @moduledoc """
  Wiring for `POST /api/v1/projects` — the write half of the pickers'
  "+ Add project…" affordance, and the first production caller of
  `Shuttle.Projects.save/1`. Every test points `SHUTTLE_PROJECTS_FILE` at a
  throwaway file so the user's real projects.json is never touched.

  Store initialization shells the real `felt init` on `PATH` (the default
  `:felt_runner`), so these tests check the store felt itself produced.
  """
  use ExUnit.Case, async: true
  import Shuttle.Test.ApiConn
  import Plug.Conn
  import Phoenix.ConnTest

  @endpoint ShuttleWeb.Endpoint

  setup do
    Shuttle.Test.Env.put_app_env(:felt_runner, Shuttle.Runner.Default)

    file =
      Path.join(
        System.tmp_dir!(),
        "shuttle-projects-ctrl-#{System.unique_integer([:positive])}.json"
      )

    Shuttle.Test.Env.delete_env("SHUTTLE_PROJECTS")
    Shuttle.Test.Env.put_env("SHUTTLE_PROJECTS_FILE", file)

    root =
      Path.join(System.tmp_dir!(), "shuttle_projects_ctrl_#{System.unique_integer([:positive])}")

    File.mkdir_p!(root)

    on_exit(fn ->
      File.rm(file)
      File.rm_rf(root)
    end)

    {:ok, root: root}
  end

  test "a plain directory is initialized as a felt store and registered", %{root: root} do
    body = post_project(root, 200)

    assert body["ok"] == true
    assert body["registered"] == true
    assert body["initialized"] == true
    assert body["path"] == Path.expand(root)
    assert body["projects"] == [Path.expand(root)]

    assert File.dir?(Path.join(root, ".felt"))
    gitignore = File.read!(Path.join([root, ".felt", ".gitignore"]))
    assert gitignore =~ ~r/\A# Generated by felt/
    lines = String.split(gitignore, "\n", trim: true)
    assert "*.md.lock" in lines
    assert ".*.tmp" in lines
    assert Shuttle.Projects.configured_projects() == [Path.expand(root)]
  end

  test "an existing store keeps its .felt untouched", %{root: root} do
    File.mkdir_p!(Path.join(root, ".felt"))
    File.write!(Path.join([root, ".felt", ".gitignore"]), "# mine\n")

    body = post_project(root, 200)

    assert body["initialized"] == false
    assert File.read!(Path.join([root, ".felt", ".gitignore"])) == "# mine\n"
  end

  defmodule FailingFelt do
    def cmd("felt", ["-C", _root, "init"], _opts), do: {"felt: permission denied\n", 1}
  end

  test "a failing felt init is a 500 that names felt's error and registers nothing", %{root: root} do
    Shuttle.Test.Env.put_app_env(:felt_runner, FailingFelt)

    body = post_project(root, 500)

    assert body["ok"] == false
    assert body["error"] =~ "felt init exited 1"
    assert body["error"] =~ "permission denied"
    assert Shuttle.Projects.configured_projects() == []
  end

  test "re-adding a registered path is an idempotent no-op success", %{root: root} do
    assert post_project(root, 200)["registered"] == true
    again = post_project(root, 200)

    assert again["ok"] == true
    assert again["registered"] == false
    assert again["projects"] == [Path.expand(root)]
    assert Shuttle.Projects.configured_projects() == [Path.expand(root)]
  end

  test "an added project joins the ones already registered", %{root: root} do
    other = Path.join(root, "sub")
    File.mkdir_p!(other)

    post_project(root, 200)
    body = post_project(other, 200)

    assert body["projects"] == [Path.expand(root), Path.expand(other)]
  end

  test "400 on a relative path" do
    assert post_project("relative/sneaky", 400)["error"] =~ "absolute"
  end

  test "400 when the path is not a directory", %{root: root} do
    file = Path.join(root, "note.txt")
    File.write!(file, "not a directory")
    assert post_project(file, 400)["error"] =~ "not a directory"
  end

  # The endpoint now takes two shapes — `path` appends one, `projects` sets the
  # whole list — so the refusal has to name both. An append-only form could
  # never say "drop this one", and a settings page that can add a checkout but
  # not remove one is a trap.
  test "400 when neither a path nor a projects list is given" do
    conn = post(api_conn(), "/api/v1/projects", Jason.encode!(%{}))
    assert conn.status == 400
    error = Jason.decode!(conn.resp_body)["error"]
    assert error =~ ~s("path")
    assert error =~ ~s("projects")
  end

  test "a projects array sets the whole list, normalized", %{root: root} do
    other = Path.join(root, "sub")
    File.mkdir_p!(other)
    post_project(root, 200)
    post_project(other, 200)

    conn =
      post(
        api_conn(),
        "/api/v1/projects",
        Jason.encode!(%{"projects" => [other, "~/loom", other, "  "]})
      )

    assert conn.status == 200
    body = Jason.decode!(conn.resp_body)
    assert body["ok"] == true
    assert body["host"] == Shuttle.Poller.own_host_id()
    assert body["projects"] == [Path.expand(other), Path.expand("~/loom")]
    assert Shuttle.Projects.configured_projects() == [Path.expand(other), Path.expand("~/loom")]

    # Setting the list neither initializes nor deletes anything on disk: the
    # path that dropped out keeps its `.felt/` exactly as it was.
    assert File.dir?(Path.join(root, ".felt"))
  end

  test "an empty projects array clears the list", %{root: root} do
    post_project(root, 200)

    conn = post(api_conn(), "/api/v1/projects", Jason.encode!(%{"projects" => []}))

    assert conn.status == 200
    assert Jason.decode!(conn.resp_body)["projects"] == []
    assert Shuttle.Projects.configured_projects() == []
  end

  test "400 when an entry in projects is not a path string" do
    conn = post(api_conn(), "/api/v1/projects", Jason.encode!(%{"projects" => ["/tmp/ok", 42]}))

    assert conn.status == 400
    assert Jason.decode!(conn.resp_body)["error"] =~ "must be a path string"
  end

  test "an unreadable project list refuses to append rather than overwrite it", %{root: root} do
    other = Path.join(root, "sub")
    File.mkdir_p!(other)
    post_project(root, 200)

    file = Shuttle.Env.get("SHUTTLE_PROJECTS_FILE")
    File.chmod!(file, 0o000)
    on_exit(fn -> File.chmod(file, 0o644) end)

    body = post_project(other, 500)
    assert body["error"] =~ "eacces"

    File.chmod!(file, 0o644)
    assert Shuttle.Projects.registered_projects() == [Path.expand(root)]
  end

  defp post_project(path, expected_status) do
    conn = post(api_conn(), "/api/v1/projects", Jason.encode!(%{"path" => path}))
    assert conn.status == expected_status
    Jason.decode!(conn.resp_body)
  end
end
