defmodule ShuttleWeb.ProjectsControllerTest do
  @moduledoc """
  Wiring for `POST /api/v1/projects` — the write half of the pickers'
  "+ Add project…" affordance, and the first production caller of
  `Shuttle.Projects.save/1`. Every test points `FELT_PROJECTS_FILE` at a
  throwaway file so the user's real projects.json is never touched.
  """
  use ExUnit.Case
  import Shuttle.Test.ApiConn
  import Shuttle.Test.EnvHelpers
  import Plug.Conn
  import Phoenix.ConnTest

  @endpoint ShuttleWeb.Endpoint

  # Byte-for-byte `internal/felt/storage.go`'s `defaultGitignore`.
  @gitignore "# Generated by felt — local fiber-write locks\n*.md.lock\n"

  setup do
    prev_env = System.get_env("FELT_PROJECTS")
    prev_file = System.get_env("FELT_PROJECTS_FILE")

    file =
      Path.join(System.tmp_dir!(), "shuttle-projects-ctrl-#{System.unique_integer([:positive])}.json")

    System.delete_env("FELT_PROJECTS")
    System.put_env("FELT_PROJECTS_FILE", file)

    root = Path.join(System.tmp_dir!(), "shuttle_projects_ctrl_#{System.unique_integer([:positive])}")
    File.mkdir_p!(root)

    on_exit(fn ->
      File.rm(file)
      File.rm_rf(root)
      restore_env("FELT_PROJECTS", prev_env)
      restore_env("FELT_PROJECTS_FILE", prev_file)
    end)

    {:ok, root: root}
  end

  test "a plain directory is initialized as a felt store and registered", %{root: root} do
    body = post_project(root, 200)

    assert body["ok"] == true
    assert body["registered"] == true
    assert body["initialized"] == true
    assert body["path"] == Path.expand(root)
    assert body["projects"] == [Path.expand(root)]

    assert File.dir?(Path.join(root, ".felt"))
    assert File.read!(Path.join([root, ".felt", ".gitignore"])) == @gitignore
    assert Shuttle.Projects.configured_projects() == [Path.expand(root)]
  end

  test "an existing store keeps its .felt untouched", %{root: root} do
    File.mkdir_p!(Path.join(root, ".felt"))
    File.write!(Path.join([root, ".felt", ".gitignore"]), "# mine\n")

    body = post_project(root, 200)

    assert body["initialized"] == false
    assert File.read!(Path.join([root, ".felt", ".gitignore"])) == "# mine\n"
  end

  test "re-adding a registered path is an idempotent no-op success", %{root: root} do
    assert post_project(root, 200)["registered"] == true
    again = post_project(root, 200)

    assert again["ok"] == true
    assert again["registered"] == false
    assert again["projects"] == [Path.expand(root)]
    assert Shuttle.Projects.configured_projects() == [Path.expand(root)]
  end

  test "an added project joins the ones already registered", %{root: root} do
    other = Path.join(root, "sub")
    File.mkdir_p!(other)

    post_project(root, 200)
    body = post_project(other, 200)

    assert body["projects"] == [Path.expand(root), Path.expand(other)]
  end

  test "400 on a relative path" do
    assert post_project("relative/sneaky", 400)["error"] =~ "absolute"
  end

  test "400 when the path is not a directory", %{root: root} do
    file = Path.join(root, "note.txt")
    File.write!(file, "not a directory")
    assert post_project(file, 400)["error"] =~ "not a directory"
  end

  test "400 when no path is given" do
    conn = post(api_conn(), "/api/v1/projects", Jason.encode!(%{}))
    assert conn.status == 400
    assert Jason.decode!(conn.resp_body)["error"] =~ "path is required"
  end

  defp post_project(path, expected_status) do
    conn = post(api_conn(), "/api/v1/projects", Jason.encode!(%{"path" => path}))
    assert conn.status == expected_status
    Jason.decode!(conn.resp_body)
  end

end
