defmodule ShuttleWeb.ProjectsController do
  @moduledoc """
  Register a checkout in the curated picker-project list:
  `POST /api/v1/projects` with `%{"path" => "<absolute path>"}`.

  The write half of the UI's "+ Add project…" affordance, and the first
  production caller of `Shuttle.Projects.save/1`. Until now the Stash/Capture
  city set could only grow by hand-editing `~/.config/felt/projects.json`; the
  directory picker (`GET /api/v1/browse`) plus this endpoint close that loop.

  Registering does two things, in order:

    1. **Ensures the directory is a felt store.** A picked folder without a
       `.felt/` is initialized here exactly as `felt init` does (Go's
       `felt.Storage.Init` — `mkdir -p <root>/.felt` plus the generated
       `.gitignore`, never overwriting an existing one). Nothing else: a felt
       store on disk IS that directory.
    2. **Appends the path to the picker list** via `Projects.save/1` (atomic
       tmp+rename). Idempotent — re-adding a registered path rewrites the same
       normalized list and reports `registered: false`.

  Read note: the list this writes is served back through
  `GET /api/v1/felt-stores` (`origins.<host>.projects`), which stays the picker's
  single source of truth. The `projects` key echoed here is the same list, so an
  agent scripting a registration needs no second call.

  **Owner-routed via `Shuttle.OriginRouter`**, like every other write: a `origin`
  naming a configured remote forwards to that daemon's identical `/projects`
  (only the owning host can create a directory on its own filesystem) and relays
  its response verbatim.

  Returns:
    200  %{ok: true, path: string, registered: bool, initialized: bool,
           host: string, projects: [string]}
    400  %{ok: false, error: string}
    500  %{ok: false, error: string}
  """

  use Phoenix.Controller, formats: [:json]
  import ShuttleWeb.RelayHelpers, only: [relay_json: 3]

  alias Shuttle.{OriginRouter, Poller, Projects}

  # Byte-for-byte the Go store initializer's output (`internal/felt/storage.go`:
  # `defaultGitignore`, written as `felt.GitignoreName`). A store initialized
  # from the UI must be indistinguishable from one `felt init` wrote.
  @default_gitignore "# Generated by felt — local fiber-write locks\n*.md.lock\n"

  def create(conn, %{"path" => path} = params) when is_binary(path) and path != "" do
    case OriginRouter.route(Map.get(params, "origin")) do
      {:remote, remote} ->
        relay_json(conn, OriginRouter.forward(remote, "/api/v1/projects", params), fn name,
                                                                                     reason ->
          %{ok: false, error: "forward to #{name} failed: #{inspect(reason)}"}
        end)

      :local ->
        register_local(conn, path)
    end
  end

  def create(conn, _params) do
    conn |> put_status(400) |> json(%{ok: false, error: "path is required"})
  end

  defp register_local(conn, raw_path) do
    trimmed = String.trim(raw_path)
    expanded = Path.expand(trimmed)

    cond do
      Path.type(trimmed) != :absolute and not String.starts_with?(trimmed, "~") ->
        conn |> put_status(400) |> json(%{ok: false, error: "path must be absolute"})

      not File.dir?(expanded) ->
        conn |> put_status(400) |> json(%{ok: false, error: "not a directory: #{expanded}"})

      true ->
        case ensure_store(expanded) do
          {:ok, initialized} -> persist(conn, expanded, initialized)
          {:error, reason} -> failed(conn, "failed to initialize felt store: #{reason}")
        end
    end
  end

  # `felt init`, in Elixir: create `.felt/` and seed its `.gitignore` when the
  # file is absent. An existing `.gitignore` is left alone — it may be the
  # human's own, and the Go initializer never overwrites one either.
  defp ensure_store(root) do
    felt_dir = Path.join(root, ".felt")
    already? = File.dir?(felt_dir)

    with :ok <- File.mkdir_p(felt_dir),
         :ok <- seed_gitignore(felt_dir) do
      {:ok, not already?}
    else
      {:error, reason} -> {:error, inspect(reason)}
    end
  end

  defp seed_gitignore(felt_dir) do
    gitignore = Path.join(felt_dir, ".gitignore")
    if File.exists?(gitignore), do: :ok, else: File.write(gitignore, @default_gitignore)
  end

  defp persist(conn, path, initialized) do
    existing = Projects.registered_projects()
    already? = path in existing

    case Projects.save(existing ++ [path]) do
      {:ok, projects} ->
        json(conn, %{
          ok: true,
          path: path,
          registered: not already?,
          initialized: initialized,
          host: Poller.own_host_id(),
          projects: projects
        })

      {:error, reason} ->
        failed(conn, "failed to persist projects: #{inspect(reason)}")
    end
  end

  defp failed(conn, message) do
    conn |> put_status(500) |> json(%{ok: false, error: message})
  end
end
