defmodule ShuttleWeb.ProjectsController do
  @moduledoc """
  Curate the picker-project list: `POST /api/v1/projects`, in two shapes.

      %{"path" => "<absolute path>"}      append one, initializing the store
      %{"projects" => ["<path>", ...]}    set the whole list

  The first is the "+ Add project…" affordance and is described below. The
  second is how a project leaves the list, which the append-only form could
  never express — a settings page that can add a checkout and not remove one is
  a trap. Setting the list neither initializes nor deletes anything on disk: it
  rewrites which directories the pickers offer, and a path that drops out keeps
  its `.felt/` exactly as it was.

  The write half of the UI's "+ Add project…" affordance, and the first
  production caller of `Shuttle.Projects.save/1`. Until now the Stash/Capture
  city set could only grow by hand-editing `~/.config/felt/projects.json`; this
  endpoint closes that loop, taking either a path the host's own folder dialog
  returned (`POST /api/v1/choose-folder`) or one the human typed for a host
  that has no dialog to raise.

  Registering does two things, in order:

    1. **Ensures the directory is a felt store.** A picked folder without a
       `.felt/` is initialized here exactly as `felt init` does (Go's
       `felt.Storage.Init` — `mkdir -p <root>/.felt` plus the generated
       `.gitignore`, never overwriting an existing one). Nothing else: a felt
       store on disk IS that directory.
    2. **Appends the path to the picker list** via `Projects.save/1` (atomic
       tmp+rename). Idempotent — re-adding a registered path rewrites the same
       normalized list and reports `registered: false`.

  Read note: the list this writes is served back through
  `GET /api/v1/felt-stores` (`origins.<host>.projects`), which stays the picker's
  single source of truth. The `projects` key echoed here is the same list, so an
  agent scripting a registration needs no second call.

  **Owner-routed via `Shuttle.OriginRouter.route_host/2`**: an `origin` naming a
  configured remote forwards to that daemon's identical `/projects` (only the
  owning host can create a directory on its own filesystem) and relays its
  response verbatim. An origin naming NOTHING this daemon can reach is refused
  rather than degraded to local — a project list exists on every host, so
  degrading would register a checkout here under another machine's name.

  Returns:
    200  %{ok: true, path: string, registered: bool, initialized: bool,
           host: string, projects: [string]}          (the append form)
    200  %{ok: true, host: string, projects: [string]} (the set form)
    400  %{ok: false, error: string}
    500  %{ok: false, error: string}
  """

  use Phoenix.Controller, formats: [:json]
  import ShuttleWeb.RelayHelpers, only: [relay_json: 3]

  alias Shuttle.{ConfigFiles, OriginRouter, Poller, Projects}

  # Byte-for-byte the Go store initializer's output (`internal/felt/storage.go`:
  # `defaultGitignore`, written as `felt.GitignoreName`). A store initialized
  # from the UI must be indistinguishable from one `felt init` wrote.
  @default_gitignore "# Generated by felt — local fiber-write locks\n*.md.lock\n"

  def create(conn, %{"path" => path} = params) when is_binary(path) and path != "" do
    case OriginRouter.route_host(Map.get(params, "origin")) do
      {:remote, remote} ->
        relay_json(conn, OriginRouter.forward(remote, "/api/v1/projects", params), fn name,
                                                                                     reason ->
          %{ok: false, error: "forward to #{name} failed: #{inspect(reason)}"}
        end)

      :local ->
        register_local(conn, path)

      {:error, {:unknown_origin, origin}} ->
        conn
        |> put_status(400)
        |> json(%{ok: false, error: OriginRouter.unknown_origin_message(origin)})
    end
  end

  def create(conn, %{"projects" => projects} = params) when is_list(projects) do
    case OriginRouter.route_host(Map.get(params, "origin")) do
      {:remote, remote} ->
        relay_json(conn, OriginRouter.forward(remote, "/api/v1/projects", params), fn name,
                                                                                     reason ->
          %{ok: false, error: "forward to #{name} failed: #{inspect(reason)}"}
        end)

      :local ->
        set_local(conn, projects, Map.get(params, "expected_digest", :any))

      {:error, {:unknown_origin, origin}} ->
        conn
        |> put_status(400)
        |> json(%{ok: false, error: OriginRouter.unknown_origin_message(origin)})
    end
  end

  def create(conn, _params) do
    conn
    |> put_status(400)
    |> json(%{ok: false, error: ~s(send a "path" to add one project, or a "projects" array to set the list)})
  end

  # Carries the same `expected_digest` precondition as the text plane: setting
  # the list is a whole-file REPLACE, so a caller working from a list someone
  # else has since changed would drop their rows without either of them seeing
  # it. Absent means last-write-wins.
  defp set_local(conn, projects, expected) do
    cond do
      not Enum.all?(projects, &is_binary/1) ->
        conn
        |> put_status(400)
        |> json(%{ok: false, error: "every entry in projects must be a path string"})

      match?({:error, _}, ConfigFiles.check_digest(:projects, expected)) ->
        {:error, message} = ConfigFiles.check_digest(:projects, expected)
        conn |> put_status(409) |> json(%{ok: false, error: message})

      true ->
        case Projects.save(projects) do
          {:ok, saved} -> json(conn, %{ok: true, host: Poller.own_host_id(), projects: saved})
          {:error, reason} -> failed(conn, "failed to persist projects: #{inspect(reason)}")
        end
    end
  end

  defp register_local(conn, raw_path) do
    trimmed = String.trim(raw_path)
    expanded = Path.expand(trimmed)

    cond do
      Path.type(trimmed) != :absolute and not String.starts_with?(trimmed, "~") ->
        conn |> put_status(400) |> json(%{ok: false, error: "path must be absolute"})

      not File.dir?(expanded) ->
        conn |> put_status(400) |> json(%{ok: false, error: "not a directory: #{expanded}"})

      true ->
        case ensure_store(expanded) do
          {:ok, initialized} -> persist(conn, expanded, initialized)
          {:error, reason} -> failed(conn, "failed to initialize felt store: #{reason}")
        end
    end
  end

  # `felt init`, in Elixir: create `.felt/` and seed its `.gitignore` when the
  # file is absent. An existing `.gitignore` is left alone — it may be the
  # human's own, and the Go initializer never overwrites one either.
  defp ensure_store(root) do
    felt_dir = Path.join(root, ".felt")
    already? = File.dir?(felt_dir)

    with :ok <- File.mkdir_p(felt_dir),
         :ok <- seed_gitignore(felt_dir) do
      {:ok, not already?}
    else
      {:error, reason} -> {:error, inspect(reason)}
    end
  end

  defp seed_gitignore(felt_dir) do
    gitignore = Path.join(felt_dir, ".gitignore")
    if File.exists?(gitignore), do: :ok, else: File.write(gitignore, @default_gitignore)
  end

  defp persist(conn, path, initialized) do
    existing = Projects.registered_projects()
    already? = path in existing

    case Projects.save(existing ++ [path]) do
      {:ok, projects} ->
        json(conn, %{
          ok: true,
          path: path,
          registered: not already?,
          initialized: initialized,
          host: Poller.own_host_id(),
          projects: projects
        })

      {:error, reason} ->
        failed(conn, "failed to persist projects: #{inspect(reason)}")
    end
  end

  defp failed(conn, message) do
    conn |> put_status(500) |> json(%{ok: false, error: message})
  end
end
