package felt

import (
	"bufio"
	"bytes"
	"errors"
	"fmt"
	"io"
	"os"
	"path"
	"path/filepath"
	"slices"
	"sort"
	"strings"
	"sync"
	"syscall"

	"gopkg.in/yaml.v3"
)

const (
	// DirName is the directory where felt files are stored.
	DirName = ".felt"
	// FileExt is the extension for felt files.
	FileExt = ".md"
	// LegacyMystConfigName is a MyST project file older felt versions wrote
	// into the store root. felt no longer creates one; the readers skip it so
	// a store that still carries one is read cleanly.
	LegacyMystConfigName = "myst.yml"
	// GitignoreName is the felt store ignore file generated at init time.
	GitignoreName = ".gitignore"
)

const defaultGitignore = `# Generated by felt — local fiber-write locks
*.md.lock
`

// Storage handles reading and writing felt files.
type Storage struct {
	root string // Path to .felt directory

	// quietWalk silences the per-file "failed to parse" and iCloud-eviction
	// warnings the listing walk prints to stderr. Those warnings exist because
	// the walk skips what it cannot read: every other command would otherwise
	// lose a fiber without saying so. `felt check` reports the same failures
	// properly, as counted issues (see CheckParseability), so it turns them off
	// rather than printing each one twice.
	quietWalk bool

	// memoWalk keeps the first store walk and reuses it (see MemoizeWalk);
	// walk is that snapshot, dropped by every write through this Storage.
	memoWalk bool
	walkMu   sync.Mutex
	walk     *storeWalk

	enclosingOnce sync.Once
	external      *ExternalRefs
}

// ErrExternalReference reports a query that names a real fiber in the
// ENCLOSING store rather than this one. It is a resolution failure — the
// fiber is not in this VIEW — but a distinguishable one, and what callers do
// with it differs: `felt check` stays quiet (the link is healthy, the view is
// narrow), while a command acting on user input reaches across and operates
// on the fiber where it lives.
//
// The sentinel exists to stop the basename rescue from stealing foreign paths
// and to tell check "not broken". It is not a fence around the enclosing
// store, and the error text deliberately suggests no command: the caller
// knows which verb the user typed, this package does not.
var ErrExternalReference = errors.New("lives in the enclosing felt store")

// ExternalReference is the resolution failure ErrExternalReference names,
// carrying enough to act on: the query as typed, the id it has in the
// enclosing store, and where that store is.
// Inferred distinguishes the two ways a query reaches out there. False means
// the query named the fiber's path exactly, from the enclosing store's root —
// someone deliberately wrote the full outer id, and there is nothing to
// remark on. True means the enclosing store's own resolver INFERRED the
// target by its scope, suffix, and basename rules; that is the case that can
// quietly outrank a local rescue, and the only one worth reporting.
//
// Guessed narrows Inferred to the inferences that are guesses: the enclosing
// store matched only a tail, a prefix or a last segment of the query, not the
// query itself from the citing fiber's position out there. Commands that
// delete or move refuse a guessed target (see FindMetadataWithoutGuessing).
type ExternalReference struct {
	Query      string
	ID         string
	Root       string // the enclosing .felt directory
	ProjectDir string // its project root — what `felt -C` takes
	Inferred   bool
	Guessed    bool
}

func (e *ExternalReference) Error() string {
	return fmt.Sprintf("%q %s as %s (%s)", e.Query, ErrExternalReference, e.ID, e.Root)
}

func (e *ExternalReference) Unwrap() error { return ErrExternalReference }

// AsExternalReference extracts the external-reference detail from an error,
// for a caller that wants to act on the fiber rather than report the failure.
func AsExternalReference(err error) (*ExternalReference, bool) {
	var ref *ExternalReference
	if errors.As(err, &ref) {
		return ref, true
	}
	return nil, false
}

// EnclosingStore reports the store this one is mounted inside, if any.
//
// A substore is a `.felt/` that is a symlink into a subdirectory of another
// `.felt/` — the project store at `<project>/.felt` pointing into the loom at
// `~/loom/.felt/<prefix>`. root is the enclosing `.felt/` directory, prefix is
// this store's slash-separated position inside it, and ok is false for an
// ordinary top-level store.
//
// s.root is the unresolved path (the symlink itself), so the answer comes
// from EvalSymlinks plus an ancestor walk looking for a `.felt` directory.
// The result is memoized: resolution consults it once per query.
func (s *Storage) EnclosingStore() (root string, prefix string, ok bool) {
	s.enclosingOnce.Do(func() {
		resolved, err := filepath.EvalSymlinks(s.root)
		if err != nil {
			return
		}
		for dir := filepath.Dir(resolved); ; dir = filepath.Dir(dir) {
			if filepath.Base(dir) == DirName && looksLikeStore(dir) {
				rel, err := filepath.Rel(dir, resolved)
				if err != nil || rel == "." || rel == ".." || strings.HasPrefix(rel, ".."+string(filepath.Separator)) {
					return
				}
				s.external = &ExternalRefs{root: dir, prefix: filepath.ToSlash(rel), cache: map[string]string{}, via: map[string]resolution{}}
				return
			}
			if parent := filepath.Dir(dir); parent == dir {
				return
			}
		}
	})
	return s.external.Root(), s.external.Prefix(), s.external != nil
}

// ExternalRefs returns the external-reference oracle for this store, or nil
// when the store is top-level (nothing is external to a store that encloses
// nothing). The nil value is usable — every method is nil-safe — so callers
// pass it along without branching. One instance per Storage, so its stat
// answers are memoized across calls.
func (s *Storage) ExternalRefs() *ExternalRefs {
	s.EnclosingStore()
	return s.external
}

// looksLikeStore reports whether dir holds felt content, so that a directory
// that is merely NAMED `.felt` — a repository checked out inside someone
// else's store, a stray fixture — is not mistaken for the store this one is
// mounted in. One ReadDir: a fiber is either a bare `<slug>.md` or a
// `<slug>/<slug>.md`, and one of either is enough.
func looksLikeStore(dir string) bool {
	entries, err := os.ReadDir(dir)
	if err != nil {
		return false
	}
	for _, entry := range entries {
		name := entry.Name()
		if !entry.IsDir() {
			if name != LegacyMystConfigName && strings.HasSuffix(name, FileExt) {
				return true
			}
			continue
		}
		if info, err := os.Stat(filepath.Join(dir, name, name+FileExt)); err == nil && !info.IsDir() {
			return true
		}
	}
	return false
}

// ExternalRefs answers, for a substore, whether a reference target names a
// fiber that lives elsewhere in the enclosing store. Two questions, both of
// which change how a query should be read from inside the substore:
//
//   - Localize: a target written with this store's own prefix
//     (`ai-futures/felt/debug`) is a LOCAL fiber spelled from the outer
//     namespace; strip the prefix and resolve the remainder in-store.
//   - Resolves: a target the ENCLOSING store resolves to a fiber outside this
//     store's prefix is genuinely elsewhere, and must not be salvaged by the
//     basename fallback into whatever local fiber shares its slug.
type ExternalRefs struct {
	root   string
	prefix string

	once     sync.Once
	resolver *scopedIDResolver

	mu    sync.Mutex
	cache map[string]string     // query -> its id out there, "" for "not out there"
	via   map[string]resolution // query -> the rule that found it out there
}

// Root is the enclosing `.felt/` directory.
func (x *ExternalRefs) Root() string {
	if x == nil {
		return ""
	}
	return x.root
}

// Prefix is this store's position inside the enclosing store.
func (x *ExternalRefs) Prefix() string {
	if x == nil {
		return ""
	}
	return x.prefix
}

// ProjectDir is the directory to hand `felt -C` to open the enclosing store.
func (x *ExternalRefs) ProjectDir() string {
	if x == nil {
		return ""
	}
	return filepath.Dir(x.root)
}

// Localize strips this store's own prefix from a query, reporting whether it
// applied.
func (x *ExternalRefs) Localize(query string) (string, bool) {
	if x == nil || x.prefix == "" {
		return query, false
	}
	rest, ok := strings.CutPrefix(query, x.prefix+"/")
	if !ok || rest == "" {
		return query, false
	}
	return rest, true
}

// LookupPath is the cheap half of the external check: query names a fiber in
// the enclosing store when `<root>/<query>/<slug>.md` is there — the canonical
// on-disk shape of a fiber. Two syscalls, memoized, no walk, which is why it
// runs on every miss rather than behind the probe gate.
//
// It answers only for ids written out in full from the enclosing store's root.
// Partial paths and bare slugs that live deeper are the walk's business.
func (x *ExternalRefs) LookupPath(query string) (string, bool) {
	if x == nil || query == "" || strings.HasPrefix(query, "/") || strings.HasPrefix(query, "..") {
		return "", false
	}
	if query == x.prefix || strings.HasPrefix(query, x.prefix+"/") {
		return "", false
	}
	key := "path\x00" + query
	x.mu.Lock()
	id, seen := x.cache[key]
	x.mu.Unlock()
	if seen {
		return id, id != ""
	}

	id = ""
	file := filepath.Join(x.root, filepath.FromSlash(query), path.Base(query)+FileExt)
	if info, err := os.Stat(file); err == nil && !info.IsDir() {
		id = query
	}
	x.mu.Lock()
	x.cache[key] = id
	x.mu.Unlock()
	return id, id != ""
}

// Lookup reports whether the enclosing store resolves query — from the
// position this store's scope occupies out there — to a fiber outside this
// store's own subtree.
//
// The test is resolution, not file existence, because that is how the links
// were written: `[[gotcha-remote-felt-index-stale-after-gitsync]]` and
// `[[portolan/patterns/switch-to-permission-mode-auto]]` name no path from
// the loom root, and both resolve cleanly from the loom by the same slug and
// suffix rules this resolver applies locally. Asking the enclosing store the
// same question the loom's own `felt check` asks is the only predicate that
// agrees with it.
//
// A hit that lands back inside this store's prefix is NOT external — it is a
// local fiber the enclosing store reached by a path this view spells
// differently — so it falls through to the local fallbacks.
//
// The enclosing store's id list is walked once, lazily: nothing here runs
// until a query has already failed to resolve locally, so a top-level store
// or a substore with clean links never pays for it.
func (x *ExternalRefs) Lookup(scopeID, query string) (string, resolution, bool) {
	if x == nil || query == "" {
		return "", resolvedExact, false
	}
	key := scopeID + "\x00" + query
	x.mu.Lock()
	found, seen := x.cache[key]
	via := x.via[key]
	x.mu.Unlock()
	if seen {
		return found, via, found != ""
	}

	x.once.Do(func() {
		outer := &Storage{root: x.root}
		files, err := outer.listFiberFiles()
		if err != nil {
			x.resolver = newScopedIDResolverIn(nil, nil)
			return
		}
		ids := make([]string, 0, len(files))
		for _, file := range files {
			ids = append(ids, file.id)
		}
		x.resolver = newScopedIDResolverIn(ids, nil)
	})

	// The citing fiber sits at <prefix>/<scopeID> in the outer namespace;
	// resolving from there is the same lexical walk the enclosing store runs.
	id, via, err := x.resolver.resolve(path.Join(x.prefix, scopeID), query)
	if err != nil || id == x.prefix || strings.HasPrefix(id, x.prefix+"/") {
		id = ""
	}

	x.mu.Lock()
	x.cache[key] = id
	x.via[key] = via
	x.mu.Unlock()
	return id, via, id != ""
}

// strayAt reports whether query, spelled from the enclosing store's root or
// from the citing fiber's position out there, names a stray fiber file in the
// enclosing store. The returned location is absolute: `.felt/` alone would
// read as this store's.
func (x *ExternalRefs) strayAt(scopeID, query string) (string, bool) {
	if x == nil {
		return "", false
	}
	outer := &Storage{root: x.root}
	candidates := []string{query}
	for _, scope := range scopeChain(path.Join(x.prefix, scopeID)) {
		candidates = append(candidates, scopedQuery(scope, query))
	}
	for _, candidate := range candidates {
		if rel, ok := outer.strayAt(candidate); ok {
			return filepath.Join(x.root, filepath.FromSlash(rel)), true
		}
	}
	return "", false
}

// err builds the resolution failure for an external target: the sentinel, the
// query, and the id it has out there — everything a caller needs to act on
// the fiber where it lives.
func (x *ExternalRefs) err(query, id string, inferred, guessed bool) error {
	return &ExternalReference{Query: query, ID: id, Root: x.root, ProjectDir: x.ProjectDir(), Inferred: inferred, Guessed: guessed}
}

type fiberFile struct {
	id         string
	path       string
	entryPoint bool   // bare `.felt/<slug>.md` at the .felt/ root
	reportPath string // sibling report.html, if any (absolute, symlink-resolved dir)
}

type MigrationEntry struct {
	OldID string
	NewID string
}

type MigrationResult struct {
	Entries []MigrationEntry
	// Strays are the stray fiber files found below the root; each is folded
	// into the directory layout unless Blocked.
	Strays                []StrayFiber
	TitleToNameIDs        []string
	RemovedDependsOnIDs   []string
	StrippedMystAnchorIDs []string
}

type IdentityBackfillResult struct {
	AssignedIDs []string
}

// NewStorage creates a storage instance for the given directory.
// The directory should be the project root (containing .felt/).
func NewStorage(projectRoot string) *Storage {
	return &Storage{
		root: filepath.Join(projectRoot, DirName),
	}
}

// Root is this store's `.felt` directory — the path that identifies the store
// a fiber was found in, which a cross-store result has to name.
func (s *Storage) Root() string { return s.root }

// Init creates the .felt directory if it doesn't exist.
func (s *Storage) Init() error {
	if err := os.MkdirAll(s.root, 0755); err != nil {
		return fmt.Errorf("creating .felt directory: %w", err)
	}
	gitignorePath := filepath.Join(s.root, GitignoreName)
	if _, err := os.Stat(gitignorePath); os.IsNotExist(err) {
		if err := os.WriteFile(gitignorePath, []byte(defaultGitignore), 0644); err != nil {
			return fmt.Errorf("writing %s: %w", GitignoreName, err)
		}
	} else if err != nil {
		return fmt.Errorf("checking %s: %w", GitignoreName, err)
	}
	return nil
}

// SilenceWalkWarnings suppresses the listing walk's stderr warnings about
// files it had to skip. Only `felt check` should use it: it reports those same
// files as issues, with an exit code behind them, and printing both would say
// the same thing twice in two different registers.
func (s *Storage) SilenceWalkWarnings() {
	s.quietWalk = true
}

// MemoizeWalk makes the store walk run once and serve every later listing,
// check and layout inspection through this Storage, so a read-only command
// that lists fibers and then inspects the layout — `felt check`, the session
// hook — pays for one walk. A write through this Storage drops the snapshot;
// files changed behind its back are not seen, which is why only read-only
// commands turn it on.
func (s *Storage) MemoizeWalk() {
	s.memoWalk = true
}

// forgetWalk drops the memoized walk after a write.
func (s *Storage) forgetWalk() {
	s.walkMu.Lock()
	s.walk = nil
	s.walkMu.Unlock()
}

// Exists returns true if the .felt directory exists.
func (s *Storage) Exists() bool {
	info, err := os.Stat(s.root)
	return err == nil && info.IsDir()
}

// Path returns the full path for a felt file. Fibers can take one of two
// on-disk shapes:
//
//   - directory form  `<.felt>/<id>/<slug>.md`   (the standard layout)
//   - bare form       `<.felt>/<dir>/<slug>.md`  (no `<slug>/` nesting)
//
// The bare form belongs to namespace roots only: the file sits directly
// inside a `.felt/` rather than in a `<slug>/` subdirectory. At depth zero
// it is the project-root fiber. At depth greater than zero it is the
// entry-point fiber of another store mounted through a symlinked
// subdirectory, which surfaces in the outer namespace one tier deeper than
// the outer root — so for a nested id the bare form is honoured only when
// `<dir>` is that symlink. Anywhere else a bare `.md` is either a companion
// file or a stray fiber (see StrayFibers), and neither is addressable as a
// fiber.
func (s *Storage) Path(id string) string {
	id = filepath.ToSlash(filepath.Clean(id))
	slug := path.Base(id)
	dir := path.Dir(id)
	dirForm := filepath.Join(s.root, filepath.FromSlash(id), slug+FileExt)
	if dir == "." {
		// Top-level: prefer the bare shape `.felt/<slug>.md` when it exists —
		// that's the project-root fiber's canonical layout when this store
		// is mounted into an outer one via a symlink at the parent level.
		// Falls back to the directory form for the standard nested layout.
		bare := filepath.Join(s.root, slug+FileExt)
		if _, err := os.Stat(bare); err == nil {
			return bare
		}
		return dirForm
	}
	// Nested ids: directory form first, so a companion `.md` beside a
	// directory-form fiber can never shadow it.
	if _, err := os.Stat(dirForm); err == nil {
		return dirForm
	}
	mount := filepath.Join(s.root, filepath.FromSlash(dir))
	if info, err := os.Lstat(mount); err == nil && info.Mode()&os.ModeSymlink != 0 {
		bare := filepath.Join(mount, slug+FileExt)
		if _, err := os.Stat(bare); err == nil {
			return bare
		}
	}
	return dirForm
}

// CheckAvailableID returns an error if the target fiber ID already exists.
func (s *Storage) CheckAvailableID(id string) error {
	id = filepath.ToSlash(filepath.Clean(strings.TrimSpace(id)))
	if id == "." || id == "" {
		return fmt.Errorf("invalid felt id")
	}
	if _, err := os.Stat(s.Path(id)); err == nil {
		return fmt.Errorf("fiber %q already exists", id)
	} else if !os.IsNotExist(err) {
		return fmt.Errorf("checking existing fiber %q: %w", id, err)
	}
	if rel, ok := s.strayAt(id); ok {
		return strayHintError(fmt.Errorf("fiber %q would collide with a stray fiber file", id), rel)
	}
	return nil
}

// Write saves a felt to disk.
func (s *Storage) Write(f *Felt) error {
	if f == nil {
		return fmt.Errorf("cannot write nil felt")
	}
	data, err := f.Marshal()
	if err != nil {
		return err
	}

	s.forgetWalk()
	path := s.Path(f.ID)
	if err := os.MkdirAll(filepath.Dir(path), 0755); err != nil {
		return fmt.Errorf("creating directory %s: %w", filepath.Dir(path), err)
	}
	if err := os.WriteFile(path, data, 0644); err != nil {
		return fmt.Errorf("writing file %s: %w", path, err)
	}
	return nil
}

// Read loads a felt from disk by ID.
func (s *Storage) Read(id string) (*Felt, error) {
	return s.readPathWithMode(s.Path(id), id, ParseFull)
}

// FindMetadataInScope returns the first felt matching the query using lexical
// scoped resolution rooted at scopeID.
func (s *Storage) FindMetadataInScope(scopeID, query string) (*Felt, error) {
	return s.findWithModeAndScope(scopeID, query, ParseMetadataOnly)
}

// FindMetadataWithoutGuessing is FindMetadataInScope for commands that delete
// or move a fiber: it refuses a guess, returning a *GuessError that names the
// fiber the guess would have reached. A guess is what `felt check` warns on —
// a multi-segment path whose written prefix matched nothing, rescued by its
// last segment — plus an in-scope prefix completion, and, from a substore, any
// answer the enclosing store infers by tail, prefix or last segment rather
// than by the query itself. Everything check accepts silently is accepted: an
// exact id, the lexical scope chain, the view's own prefix, a unique bare slug
// and a correct partial tail.
func (s *Storage) FindMetadataWithoutGuessing(scopeID, query string) (*Felt, error) {
	f, via, err := s.find(scopeID, query, ParseMetadataOnly)
	if ref, ok := AsExternalReference(err); ok && ref.Guessed {
		return nil, &GuessError{Query: query, Guess: ref.ID, Root: ref.Root}
	}
	if err != nil {
		return nil, err
	}
	if via.guess() {
		return nil, &GuessError{Query: query, Guess: f.ID}
	}
	return f, nil
}

// GuessError is a query that only a guess resolves — to Guess, in the
// enclosing store at Root when set (see FindMetadataWithoutGuessing).
type GuessError struct {
	Query string
	Guess string
	Root  string
}

func (e *GuessError) Error() string {
	where := ""
	if e.Root != "" {
		where = fmt.Sprintf(" (in %s)", e.Root)
	}
	return fmt.Sprintf("%q only reaches a fiber by guessing, and this command does not act on a guess; did you mean %s%s?", e.Query, e.Guess, where)
}

// FindExistingMetadataInScope resolves only direct on-disk candidates in the
// lexical scope chain. It intentionally does not fall back to walking the whole
// store, so narrow read paths can annotate exact refs without surprise work.
func (s *Storage) FindExistingMetadataInScope(scopeID, query string) (*Felt, bool, error) {
	return s.findExistingPathWithModeAndScope(scopeID, query, ParseMetadataOnly)
}

// readPathWithMode reads a fiber from a known on-disk path. Used by list-time
// callers that already discovered the file via the walk and shouldn't re-derive
// the path from the id (which loses information when ids cross symlink
// boundaries — e.g. an entry-point bare-form fiber inside a symlinked
// sub-store has no recoverable shape from the prefixed id alone).
func (s *Storage) readPathWithMode(path, id string, mode ParseMode) (*Felt, error) {
	// Canonicalize the on-disk path once so every surface (walk-time list and
	// direct single-read) carries the same absolute, symlink-resolved location
	// — the real "where the bytes are". Walk-time paths are already resolved,
	// so EvalSymlinks is a no-op there; the single-read path is computed via
	// s.Path(id) against the (possibly symlinked) store root, so resolving here
	// keeps it from leaking a symlink-traversing path. Reads still use the
	// original `path` (resolved is only what we carry on f.Path); fall back to
	// the original if resolution fails so a transient stat error can't drop the
	// path entirely.
	carriedPath := path
	if resolved, err := filepath.EvalSymlinks(path); err == nil {
		carriedPath = resolved
	}

	var f *Felt
	if mode == ParseMetadataOnly {
		var err error
		if f, err = readMetadataFile(path, id); err != nil {
			return nil, fmt.Errorf("reading file %s: %w", path, err)
		}
	} else {
		data, err := os.ReadFile(path)
		if err != nil {
			return nil, fmt.Errorf("reading file %s: %w", path, err)
		}
		if f, err = ParseWithMode(id, data, mode); err != nil {
			return nil, err
		}
	}
	// Carry the on-disk path so consumers read it instead of
	// reconstructing it from the id.
	f.Path = carriedPath
	return f, nil
}

// Delete removes a felt from disk.
func (s *Storage) Delete(id string) error {
	s.forgetWalk()
	path := s.Path(id)
	if err := os.Remove(path); err != nil {
		return fmt.Errorf("deleting file %s: %w", path, err)
	}
	return s.pruneEmptyDirs(filepath.Dir(path))
}

// pruneEmptyDirs removes now-empty ancestor directories, walking from startDir
// up toward (but never including) the store root. It stops at the first
// non-empty directory; any other removal error is reported.
func (s *Storage) pruneEmptyDirs(startDir string) error {
	for dir := startDir; dir != s.root; dir = filepath.Dir(dir) {
		err := os.Remove(dir)
		if err == nil {
			continue
		}
		if errors.Is(err, syscall.ENOTEMPTY) {
			break
		}
		return fmt.Errorf("cleaning directory %s: %w", dir, err)
	}
	return nil
}

// MoveResult names the fibers whose files a move rewrote, by their ids after
// the move. Outside holds fibers of the enclosing store, outside this view,
// by their ids there.
type MoveResult struct {
	Rewritten []string
	Outside   []string
}

// MoveSubtree moves a fiber and any nested descendants to a new path, rewriting
// the references whose meaning the move would otherwise change.
//
// A reference — body link or inputs.from — is rewritten when its path resolved
// before the move and no longer resolves to the same fiber after it: one left
// pointing at the old path, or one the moved fibers would capture (see
// rewriteMovedRef). When this store is a view into an
// enclosing store, the enclosing store's fibers outside the view are rewritten
// the same way, in its own coordinates: links from other projects are the ones
// a move inside a view would otherwise leave behind. Only files whose content
// changes are written; a moved fiber's id is its location, not its content,
// so the rename alone moves it.
func (s *Storage) MoveSubtree(oldID, newID string) (*MoveResult, error) {
	oldID = filepath.ToSlash(filepath.Clean(strings.TrimSpace(oldID)))
	newID = filepath.ToSlash(filepath.Clean(strings.TrimSpace(newID)))
	if oldID == "." || oldID == "" || newID == "." || newID == "" {
		return nil, fmt.Errorf("invalid felt id")
	}
	if oldID == newID {
		return nil, fmt.Errorf("source and destination are the same")
	}
	if strings.HasPrefix(newID, oldID+"/") {
		return nil, fmt.Errorf("cannot move %s into its own subtree %s", oldID, newID)
	}
	if _, err := os.Stat(s.Path(newID)); err == nil {
		return nil, fmt.Errorf("destination %s already exists", newID)
	} else if !os.IsNotExist(err) {
		return nil, fmt.Errorf("checking destination %s: %w", newID, err)
	}

	felts, err := s.List()
	if err != nil {
		return nil, err
	}
	movedAny := false
	for _, f := range felts {
		if _, ok := remapIDPrefix(f.ID, oldID, newID); ok {
			movedAny = true
			break
		}
	}
	if !movedAny {
		return nil, fmt.Errorf("no fiber found at %s", oldID)
	}

	external := s.ExternalRefs()
	writes, err := planMoveRewrites(felts, felts, external, oldID, newID)
	if err != nil {
		return nil, err
	}
	var outsideWrites []pendingWrite
	if external != nil {
		outsideWrites, err = s.planOutsideRewrites(external, oldID, newID)
		if err != nil {
			return nil, err
		}
	}

	oldRoot := filepath.Join(s.root, filepath.FromSlash(oldID))
	newRoot := filepath.Join(s.root, filepath.FromSlash(newID))
	if _, err := os.Stat(newRoot); err == nil {
		return nil, fmt.Errorf("destination %s already exists", newID)
	} else if !os.IsNotExist(err) {
		return nil, fmt.Errorf("checking destination directory %s: %w", newID, err)
	}
	if err := os.MkdirAll(filepath.Dir(newRoot), 0755); err != nil {
		return nil, fmt.Errorf("creating destination parent %s: %w", filepath.Dir(newRoot), err)
	}
	s.forgetWalk()
	if err := os.Rename(oldRoot, newRoot); err != nil {
		return nil, fmt.Errorf("moving subtree %s -> %s: %w", oldRoot, newRoot, err)
	}

	result := &MoveResult{}
	for _, w := range writes {
		if err := w.write(s); err != nil {
			return result, err
		}
		result.Rewritten = append(result.Rewritten, w.id)
	}
	for _, w := range outsideWrites {
		if err := w.write(s); err != nil {
			return result, err
		}
		result.Outside = append(result.Outside, w.id)
	}
	sort.Strings(result.Rewritten)
	sort.Strings(result.Outside)
	return result, s.pruneEmptyDirs(filepath.Dir(oldRoot))
}

// pendingWrite is a fiber file's new content, planned before the move and
// written after it. path is where the file already is; empty means the fiber
// moved, and its file is found by id once the rename has happened.
type pendingWrite struct {
	id   string
	path string
	data []byte
}

func (w pendingWrite) write(s *Storage) error {
	path := w.path
	if path == "" {
		path = s.Path(w.id)
	}
	if err := os.WriteFile(path, w.data, 0644); err != nil {
		return fmt.Errorf("writing file %s: %w", path, err)
	}
	return nil
}

// planOutsideRewrites plans the rewrites in the enclosing store's fibers
// outside this view. Addresses there are outer ids, so the move is lifted by
// this store's prefix; the outer resolvers see every outer id, the view's
// included, but only the fibers outside it are sources — the view's own were
// planned in its coordinates.
func (s *Storage) planOutsideRewrites(external *ExternalRefs, oldID, newID string) ([]pendingWrite, error) {
	prefix := external.Prefix()
	outer := &Storage{root: external.Root()}
	all, err := outer.List()
	if err != nil {
		return nil, err
	}
	outside := make([]*Felt, 0, len(all))
	for _, f := range all {
		if f.ID != prefix && !strings.HasPrefix(f.ID, prefix+"/") {
			outside = append(outside, f)
		}
	}
	return planMoveRewrites(all, outside, nil, path.Join(prefix, oldID), path.Join(prefix, newID))
}

// planMoveRewrites plans the file rewrites for sources when oldID moves to
// newID within the id space of all.
func planMoveRewrites(all, sources []*Felt, external *ExternalRefs, oldID, newID string) ([]pendingWrite, error) {
	oldIDs := make([]string, 0, len(all))
	newIDs := make([]string, 0, len(all))
	for _, f := range all {
		oldIDs = append(oldIDs, f.ID)
		remapped, _ := remapIDPrefix(f.ID, oldID, newID)
		newIDs = append(newIDs, remapped)
	}
	sort.Strings(oldIDs)
	sort.Strings(newIDs)
	before := newScopedIDResolverIn(oldIDs, external)
	after := newScopedIDResolverIn(newIDs, external)

	var writes []pendingWrite
	for _, f := range sources {
		sourceNew, moved := remapIDPrefix(f.ID, oldID, newID)
		rewrite := func(target string) (string, bool) {
			return rewriteMovedRef(before, after, f.ID, sourceNew, target, oldID, newID)
		}
		clone := *f
		clone.ID = sourceNew
		flowChanged := clone.RewriteDataFlowRefs(func(ref string) (string, bool) {
			target, fragment := splitDataFlowRef(ref)
			next, ok := rewrite(target)
			if !ok {
				return ref, false
			}
			if fragment != "" {
				next += "." + fragment
			}
			return next, true
		})
		body, bodyChanged := RewriteBodyRefs(f.Body, rewrite)
		if !flowChanged && !bodyChanged {
			continue
		}

		var data []byte
		var err error
		if flowChanged {
			// inputs.from lives in frontmatter, so the file is re-rendered.
			clone.Body = body
			data, err = clone.Marshal()
		} else {
			// A body-only change edits the body bytes in place, leaving the
			// frontmatter exactly as its author wrote it.
			data, err = rewriteFileBody(f.Path, rewrite)
		}
		if err != nil {
			return nil, fmt.Errorf("rewriting references in %s: %w", f.ID, err)
		}
		w := pendingWrite{id: sourceNew, path: f.Path, data: data}
		if moved {
			w.path = ""
		}
		writes = append(writes, w)
	}
	return writes, nil
}

// rewriteMovedRef decides one reference's fate when oldID moves to newID. The
// source fiber sits at sourceOld before the move and sourceNew after it.
//
// A reference is rewritten only when its path resolved before the move and
// does not resolve by path to the same fiber after it — the same fiber being
// the one it named, at its new id if it moved. That covers a path into the
// moved subtree that the move leaves behind, and a path to a fiber that stays
// put but that the move would capture: [[x]] naming a/xy by prefix from a/sib
// comes to name a/x once x is nested under a, so it is pinned to a/xy. It
// leaves alone every spelling the move does not change — a bare slug or a
// suffix that still names its fiber uniquely, a scope-relative path that moved
// with its scope — as well as links that already resolved only by the
// basename rescue.
//
// The new spelling keeps the reference's shape where it can: a path written
// relative to a scope stays relative to that scope, and one written from the
// enclosing store's namespace stays in it. Failing that, it is the full id.
func rewriteMovedRef(before, after *scopedIDResolver, sourceOld, sourceNew, target, oldID, newID string) (string, bool) {
	target = cleanLookupQuery(target)
	resolved, ok := before.ResolvePath(sourceOld, target)
	if !ok {
		return "", false
	}
	destination, _ := remapIDPrefix(resolved, oldID, newID)
	if got, ok := after.ResolvePath(sourceNew, target); ok && got == destination {
		return "", false
	}

	var candidates []string
	if anchor, ok := strings.CutSuffix(resolved, "/"+target); ok {
		if rest, ok := strings.CutPrefix(destination, anchor+"/"); ok {
			candidates = append(candidates, rest)
		}
	} else if prefix := after.external.Prefix(); prefix != "" && target == prefix+"/"+resolved {
		candidates = append(candidates, prefix+"/"+destination)
	}
	for _, candidate := range candidates {
		if got, ok := after.ResolvePath(sourceNew, candidate); ok && got == destination {
			return candidate, true
		}
	}
	return destination, true
}

// rewriteFileBody applies rewrite to the body references of the fiber file at
// path, returning the file's new bytes with its frontmatter untouched.
func rewriteFileBody(path string, rewrite func(string) (string, bool)) ([]byte, error) {
	content, err := os.ReadFile(path)
	if err != nil {
		return nil, err
	}
	_, _, bodyStart, err := frontmatterBounds(content)
	if err != nil {
		return nil, err
	}
	body, _ := RewriteBodyRefs(string(content[bodyStart:]), rewrite)
	out := make([]byte, 0, bodyStart+len(body))
	out = append(out, content[:bodyStart]...)
	return append(out, body...), nil
}

// Migrate performs the storage-model normalization pass:
// flat-file fibers become directory fibers, stray fiber files fold into the
// directory layout, legacy frontmatter `title` fields become `name`, and
// leading MyST anchor lines are stripped from bodies.
func (s *Storage) Migrate(dryRun bool) (*MigrationResult, error) {
	result, err := s.MigrateFlatFiles(dryRun)
	if err != nil {
		return nil, err
	}

	if result.Strays, err = s.StrayFibers(); err != nil {
		return nil, err
	}
	if !dryRun {
		// A fold that fails is reported like a blocked one and the pass goes
		// on: the folds before it are done, and stopping here would hide them
		// and skip the normalization below.
		for i := range result.Strays {
			sf := &result.Strays[i]
			if sf.Blocked != "" {
				continue
			}
			if err := sf.fold(); err != nil {
				sf.Blocked = err.Error()
			}
		}
		s.forgetWalk()
	}

	if err := s.normalizeFiberFiles(dryRun, result); err != nil {
		return nil, err
	}
	return result, nil
}

// MigrateFlatFiles converts legacy top-level flat markdown fibers to
// directory-based fibers with slug IDs, rewriting data-flow references.
func (s *Storage) MigrateFlatFiles(dryRun bool) (*MigrationResult, error) {
	if err := s.Init(); err != nil {
		return nil, err
	}

	entries, err := os.ReadDir(s.root)
	if err != nil {
		return nil, fmt.Errorf("reading .felt directory: %w", err)
	}

	type legacyFiber struct {
		oldID string
		path  string
		felt  *Felt
	}

	var legacy []legacyFiber
	for _, entry := range entries {
		if entry.IsDir() {
			continue
		}
		name := entry.Name()
		if name == LegacyMystConfigName || filepath.Ext(name) != FileExt {
			continue
		}
		oldID := strings.TrimSuffix(name, FileExt)
		data, err := os.ReadFile(filepath.Join(s.root, name))
		if err != nil {
			return nil, fmt.Errorf("reading legacy fiber %s: %w", name, err)
		}
		f, err := Parse(oldID, data)
		if err != nil {
			return nil, fmt.Errorf("parsing legacy fiber %s: %w", name, err)
		}
		legacy = append(legacy, legacyFiber{
			oldID: oldID,
			path:  filepath.Join(s.root, name),
			felt:  f,
		})
	}

	// Exactly one bare root .md is assumed the entry-point fiber and left
	// untouched; with two or more we can't tell entry-point from stray, so all
	// are migrated (to <slug>/<slug>.md form).
	if len(legacy) == 1 {
		return &MigrationResult{}, nil
	}

	result := &MigrationResult{Entries: make([]MigrationEntry, 0, len(legacy))}
	if len(legacy) == 0 {
		return result, nil
	}

	used := map[string]struct{}{}
	for _, f := range legacy {
		baseID, err := GenerateID(f.felt.DisplayName())
		if err != nil {
			return nil, fmt.Errorf("generate slug for %s: %w", f.oldID, err)
		}
		newID, err := s.nextAvailableMigrationID(baseID, used)
		if err != nil {
			return nil, err
		}
		used[newID] = struct{}{}
		result.Entries = append(result.Entries, MigrationEntry{
			OldID: f.oldID,
			NewID: newID,
		})
	}

	slices.SortFunc(result.Entries, func(a, b MigrationEntry) int {
		return strings.Compare(a.OldID, b.OldID)
	})

	if dryRun {
		return result, nil
	}

	idMap := map[string]string{}
	for _, entry := range result.Entries {
		idMap[entry.OldID] = entry.NewID
	}
	remap := func(ref string) (string, bool) {
		targetFiber, fragment := splitDataFlowRef(ref)
		newID, ok := idMap[targetFiber]
		if !ok {
			return "", false
		}
		if fragment == "" {
			return newID, true
		}
		return newID + "." + fragment, true
	}

	for _, item := range legacy {
		f := item.felt
		f.ID = idMap[item.oldID]
		f.RewriteDataFlowRefs(func(ref string) (string, bool) {
			if remappedFrom, ok := remapDataFlowRef(ref, item.oldID, f.ID); ok {
				return remappedFrom, true
			}
			return remap(ref)
		})
		if err := s.Write(f); err != nil {
			return nil, err
		}
	}

	for _, item := range legacy {
		if err := os.Remove(item.path); err != nil {
			return nil, fmt.Errorf("removing legacy fiber %s: %w", item.path, err)
		}
	}

	// Rewrite stale hex-suffixed data-flow refs in pre-existing directory fibers.
	allFibers, err := s.List()
	if err != nil {
		return nil, fmt.Errorf("listing fibers for input rewrite: %w", err)
	}
	for _, f := range allFibers {
		changed := f.RewriteDataFlowRefs(remap)
		if changed {
			if err := s.Write(f); err != nil {
				return nil, fmt.Errorf("rewriting inputs in %s: %w", f.ID, err)
			}
		}
	}

	return result, nil
}

// normalizeFiberFiles rewrites legacy per-file format details in-place:
// frontmatter `title` -> `name`, and leading MyST anchor lines in bodies.
func (s *Storage) normalizeFiberFiles(dryRun bool, result *MigrationResult) error {
	files, err := s.listFiberFiles()
	if err != nil {
		return err
	}

	for _, file := range files {
		data, err := os.ReadFile(file.path)
		if err != nil {
			return fmt.Errorf("reading fiber %s: %w", file.path, err)
		}

		rewritten, renamedTitle, removedDependsOn, strippedAnchor, err := normalizeFiberFile(file.id, data)
		if err != nil {
			return fmt.Errorf("normalize fiber %s: %w", file.path, err)
		}
		if !renamedTitle && !removedDependsOn && !strippedAnchor {
			continue
		}
		if renamedTitle {
			result.TitleToNameIDs = append(result.TitleToNameIDs, file.id)
		}
		if removedDependsOn {
			result.RemovedDependsOnIDs = append(result.RemovedDependsOnIDs, file.id)
		}
		if strippedAnchor {
			result.StrippedMystAnchorIDs = append(result.StrippedMystAnchorIDs, file.id)
		}
		if dryRun {
			continue
		}
		if err := os.WriteFile(file.path, rewritten, 0644); err != nil {
			return fmt.Errorf("writing normalized fiber %s: %w", file.path, err)
		}
	}

	slices.Sort(result.TitleToNameIDs)
	slices.Sort(result.RemovedDependsOnIDs)
	slices.Sort(result.StrippedMystAnchorIDs)
	return nil
}

// BackfillIntrinsicIDs assigns an intrinsic ULID to every fiber missing one.
// This is intentionally separate from Migrate: replicas must not run it
// casually, or the same git-synced fiber can split into multiple identities.
func (s *Storage) BackfillIntrinsicIDs(dryRun bool) (*IdentityBackfillResult, error) {
	files, err := s.listFiberFiles()
	if err != nil {
		return nil, err
	}

	result := &IdentityBackfillResult{}
	for _, file := range files {
		data, err := os.ReadFile(file.path)
		if err != nil {
			return nil, fmt.Errorf("reading fiber %s: %w", file.path, err)
		}
		rewritten, changed, err := backfillIntrinsicID(data)
		if err != nil {
			fmt.Fprintf(os.Stderr, "warning: failed to backfill %s: %v\n", file.path, err)
			continue
		}
		if !changed {
			continue
		}
		result.AssignedIDs = append(result.AssignedIDs, file.id)
		if dryRun {
			continue
		}
		if err := os.WriteFile(file.path, rewritten, 0644); err != nil {
			return nil, fmt.Errorf("writing identity-backfilled fiber %s: %w", file.path, err)
		}
	}

	slices.Sort(result.AssignedIDs)
	return result, nil
}

func normalizeFiberFile(id string, content []byte) ([]byte, bool, bool, bool, error) {
	frontmatter, body, err := SplitFrontmatter(content, true)
	if err != nil {
		return nil, false, false, false, err
	}

	rewrittenFrontmatter, renamedTitle, removedDependsOn, err := normalizeLegacyFrontmatter(frontmatter)
	if err != nil {
		return nil, false, false, false, err
	}
	rewrittenBody, strippedAnchor := stripLegacyMystAnchor(id, body)
	if !renamedTitle && !removedDependsOn && !strippedAnchor {
		return content, false, false, false, nil
	}

	var out bytes.Buffer
	out.WriteString("---\n")
	out.Write(rewrittenFrontmatter)
	out.WriteString("---\n")
	if rewrittenBody != "" {
		out.WriteString("\n")
		out.WriteString(rewrittenBody)
		if !strings.HasSuffix(rewrittenBody, "\n") {
			out.WriteString("\n")
		}
	}
	return out.Bytes(), renamedTitle, removedDependsOn, strippedAnchor, nil
}

func backfillIntrinsicID(content []byte) ([]byte, bool, error) {
	frontmatter, body, err := SplitFrontmatter(content, true)
	if err != nil {
		return nil, false, err
	}

	rewrittenFrontmatter, changed, err := backfillIntrinsicIDFrontmatter(frontmatter)
	if err != nil {
		return nil, false, err
	}
	if !changed {
		return content, false, nil
	}

	var out bytes.Buffer
	out.WriteString("---\n")
	out.Write(rewrittenFrontmatter)
	out.WriteString("---\n")
	if body != "" {
		out.WriteString(body)
	}
	return out.Bytes(), true, nil
}

func backfillIntrinsicIDFrontmatter(frontmatter []byte) ([]byte, bool, error) {
	mapping, err := frontmatterMappingNode(frontmatter)
	if err != nil {
		return nil, false, err
	}
	if mapping == nil {
		return frontmatter, false, nil
	}

	for i := 0; i+1 < len(mapping.Content); i += 2 {
		if mapping.Content[i].Value == "id" && strings.TrimSpace(mapping.Content[i+1].Value) != "" {
			return frontmatter, false, nil
		}
	}

	idKey := &yaml.Node{Kind: yaml.ScalarNode, Tag: "!!str", Value: "id"}
	idValue := &yaml.Node{Kind: yaml.ScalarNode, Tag: "!!str", Value: NewULID()}
	mapping.Content = append([]*yaml.Node{idKey, idValue}, mapping.Content...)

	rewritten, err := yaml.Marshal(mapping)
	if err != nil {
		return nil, false, fmt.Errorf("marshaling YAML frontmatter: %w", err)
	}
	return rewritten, true, nil
}

// List returns all felts in the storage.
func (s *Storage) List() ([]*Felt, error) {
	return s.listWithModeHavingFrontmatterFields(ParseFull, false, nil)
}

// ListMetadata returns all felts with frontmatter only.
func (s *Storage) ListMetadata() ([]*Felt, error) {
	return s.listWithModeHavingFrontmatterFields(ParseMetadataOnly, false, nil)
}

// ListMetadataHavingFrontmatterFields returns metadata for fibers whose raw
// frontmatter contains all requested top-level keys. It is a narrow listing
// path for machine consumers that need only one tool-owned namespace (for
// example, every fiber with a `shuttle:` block) and should not pay a full YAML
// parse for unrelated fibers.
func (s *Storage) ListMetadataHavingFrontmatterFields(fields []string) ([]*Felt, error) {
	return s.listWithModeHavingFrontmatterFields(ParseMetadataOnly, false, fields)
}

// ListMetadataWithModTime returns metadata plus file modification times.
func (s *Storage) ListMetadataWithModTime() ([]*Felt, error) {
	return s.listWithModeHavingFrontmatterFields(ParseMetadataOnly, true, nil)
}

// ListMetadataWithModTimeHavingFrontmatterFields returns metadata plus file
// modification times for fibers whose raw frontmatter contains all requested
// top-level keys.
func (s *Storage) ListMetadataWithModTimeHavingFrontmatterFields(fields []string) ([]*Felt, error) {
	return s.listWithModeHavingFrontmatterFields(ParseMetadataOnly, true, fields)
}

func (s *Storage) listWithModeHavingFrontmatterFields(mode ParseMode, includeModTime bool, fields []string) ([]*Felt, error) {
	files, err := s.listFiberFiles()
	if err != nil {
		return nil, err
	}

	var felts []*Felt
	evicted := 0 // iCloud-dataless files that couldn't be materialized during the walk
	note := func(p string, err error) {
		if isEvictedFileError(err) {
			evicted++
		} else if !s.quietWalk {
			fmt.Fprintf(os.Stderr, "warning: failed to parse %s: %v\n", p, err)
		}
	}
	for _, file := range files {
		if len(fields) > 0 && mode == ParseMetadataOnly {
			matched, err := fileFrontmatterHasTopLevelFields(file.path, fields)
			if err != nil {
				note(file.path, err)
				continue
			}
			if !matched {
				continue
			}
		}
		f, err := s.readPathWithMode(file.path, file.id, mode)
		if err != nil {
			note(file.path, err)
			continue
		}
		if includeModTime {
			if info, err := os.Stat(file.path); err == nil {
				f.ModifiedAt = info.ModTime()
			}
		}
		f.EntryPoint = file.entryPoint
		f.ReportPath = file.reportPath
		felts = append(felts, f)
	}

	if evicted > 0 && !s.quietWalk {
		fmt.Fprintf(os.Stderr, "warning: %d file(s) not materialized (iCloud) under %s; run `brctl download` or open them in Files to hydrate\n", evicted, s.root)
	}

	return felts, nil
}

// isEvictedFileError reports whether err is the failure signature of an
// iCloud-dataless file — one whose metadata is present but whose contents
// haven't been downloaded locally. Reading such a file returns EDEADLK
// ("resource deadlock avoided") on macOS as the CloudDocs daemon declines to
// fault it in synchronously. We match the errno directly (portable via
// syscall) and fall back to a conservative string match so the same eviction
// signature is recognized even when wrapped without an errno.
func isEvictedFileError(err error) bool {
	if err == nil {
		return false
	}
	if errors.Is(err, syscall.EDEADLK) {
		return true
	}
	return strings.Contains(err.Error(), "resource deadlock avoided")
}

// FindInScope returns the first felt matching the query using lexical scoped
// resolution rooted at scopeID.
func (s *Storage) FindInScope(scopeID, query string) (*Felt, error) {
	return s.findWithModeAndScope(scopeID, query, ParseFull)
}

// findWithModeAndScope is the single fiber-resolution implementation behind
// FindInScope / FindMetadataInScope / FindExistingMetadataInScope: it tries
// direct on-disk scope-chain candidates first, then falls back to a full-store
// scan with slug and (UID-shaped) exact-UID matching.
func (s *Storage) findWithModeAndScope(scopeID, query string, mode ParseMode) (*Felt, error) {
	f, _, err := s.find(scopeID, query, mode)
	return f, err
}

// find is findWithModeAndScope, also reporting which rule answered.
func (s *Storage) find(scopeID, query string, mode ParseMode) (*Felt, resolution, error) {
	if f, ok, err := s.findExistingPathWithModeAndScope(scopeID, query, mode); ok || err != nil {
		return f, resolvedExact, err
	}

	files, loose, err := s.walkStore()
	if err != nil {
		return nil, resolvedExact, err
	}

	query = cleanLookupQuery(query)
	scopeID = cleanLookupScope(scopeID)

	pathByID := make(map[string]string, len(files))
	ids := make([]string, 0, len(files))
	for _, file := range files {
		pathByID[file.id] = file.path
		ids = append(ids, file.id)
	}

	matchID, via, err := newScopedIDResolverIn(ids, s.ExternalRefs()).resolve(scopeID, query)
	if err != nil {
		// Slug resolution missed. If the query is UID-shaped, fall back to an
		// exact-UID walk: the UID lives in frontmatter (not the path-derived
		// id), so it isn't in `ids`. ULIDs never collide with slugs, so this is
		// purely additive — it only runs when slug resolution already failed.
		if LooksLikeUID(query) {
			if f, ok, uidErr := s.findByUIDWithMode(files, query, mode); ok || uidErr != nil {
				return f, resolvedExact, uidErr
			}
		}
		return nil, via, withStrayHint(err, query, loose)
	}
	f, err := s.readPathWithMode(pathByID[matchID], matchID, mode)
	if err != nil {
		return nil, via, err
	}
	if info, err := os.Stat(pathByID[matchID]); err == nil {
		f.ModifiedAt = info.ModTime()
	}
	return f, via, nil
}

// findByUIDWithMode resolves a fiber by an exact (case-insensitive) UID match.
// The UID is frontmatter-only, so this walks the file list parsing metadata to
// read each UID; the caller gates it on LooksLikeUID so the scan only runs for
// UID-shaped queries that slug resolution already failed to resolve.
func (s *Storage) findByUIDWithMode(files []fiberFile, query string, mode ParseMode) (*Felt, bool, error) {
	for _, file := range files {
		meta, err := s.readPathWithMode(file.path, file.id, ParseMetadataOnly)
		if err != nil {
			continue
		}
		if !meta.MatchesUID(query) {
			continue
		}
		f, err := s.readPathWithMode(file.path, file.id, mode)
		if err != nil {
			return nil, true, err
		}
		if info, statErr := os.Stat(file.path); statErr == nil {
			f.ModifiedAt = info.ModTime()
		}
		return f, true, nil
	}
	return nil, false, nil
}

func (s *Storage) findExistingPathWithModeAndScope(scopeID, query string, mode ParseMode) (*Felt, bool, error) {
	query = cleanLookupQuery(query)
	if query == "" || !validLookupID(query) {
		return nil, false, nil
	}
	scopeID = cleanLookupScope(scopeID)
	if scopeID != "" && !validLookupID(scopeID) {
		return nil, false, nil
	}
	var candidates []string
	if strings.Contains(query, "/") {
		candidates = []string{query}
	}
	for _, scope := range scopeChain(scopeID) {
		candidates = append(candidates, scopedQuery(scope, query))
	}
	// A query spelled with this store's own prefix in the enclosing store's
	// namespace names a local fiber — but only once the query's own spelling
	// has come up empty, so a local id that really starts with the prefix
	// keeps its address. Hence: appended last, never substituted.
	if local, stripped := s.ExternalRefs().Localize(query); stripped {
		if strings.Contains(local, "/") {
			candidates = append(candidates, local)
		}
		for _, scope := range scopeChain(scopeID) {
			candidates = append(candidates, scopedQuery(scope, local))
		}
	}

	seen := make(map[string]struct{}, len(candidates))
	for _, candidate := range candidates {
		candidate = path.Clean(candidate)
		if _, ok := seen[candidate]; ok {
			continue
		}
		seen[candidate] = struct{}{}

		f, ok, err := s.readExistingPathWithMode(candidate, mode)
		if ok || err != nil {
			return f, ok, err
		}
		// A candidate that names a stray fiber file stops the lookup: the
		// query means that file, and every later rule — a farther scope, the
		// slug rescue — would answer with a different fiber that `rm` or
		// `nest` then acts on.
		if rel, stray := s.strayAt(candidate); stray {
			return nil, false, strayHintError(fmt.Errorf("no fiber found matching %q", query), rel)
		}
	}
	return nil, false, nil
}

func validLookupID(id string) bool {
	return id != ".." && !strings.HasPrefix(id, "../") && !path.IsAbs(id)
}

func (s *Storage) readExistingPathWithMode(id string, mode ParseMode) (*Felt, bool, error) {
	filePath := s.Path(id)
	if !s.pathInStore(filePath) {
		return nil, false, nil
	}
	info, err := os.Stat(filePath)
	if os.IsNotExist(err) {
		return nil, false, nil
	}
	if err != nil {
		return nil, false, fmt.Errorf("checking file %s: %w", filePath, err)
	}
	if info.IsDir() {
		return nil, false, nil
	}

	f, err := s.readPathWithMode(filePath, id, mode)
	if err != nil {
		return nil, true, err
	}
	f.ModifiedAt = info.ModTime()
	return f, true, nil
}

func (s *Storage) pathInStore(filePath string) bool {
	root := filepath.Clean(s.root)
	filePath = filepath.Clean(filePath)
	rel, err := filepath.Rel(root, filePath)
	return err == nil && rel != "." && !strings.HasPrefix(rel, ".."+string(filepath.Separator)) && rel != ".."
}

func (s *Storage) listFiberFiles() ([]fiberFile, error) {
	files, _, err := s.walkStore()
	return files, err
}

// looseFile is a markdown file the walk passed over: it sits below a walk
// tier's root and its stem differs from its directory's name, so it is not
// any fiber's own `<slug>.md`. Companion notes and stray fibers both take this
// shape; strayFibersIn tells them apart by content. A file whose path in the
// store — mount points included — has a hidden segment (an editor's
// `.trash/`, say) is never collected.
type looseFile struct {
	path    string // on-disk path
	rel     string // slash-separated path in the store's logical namespace
	symlink bool   // the file itself is a symlink
}

// hiddenPath reports whether any segment of a slash-separated store path is
// hidden.
func hiddenPath(rel string) bool {
	return strings.HasPrefix(rel, ".") || strings.Contains(rel, "/.")
}

// walkStore walks the store once, returning the fiber files and the loose
// markdown files beside them.
func (s *Storage) walkStore() ([]fiberFile, []looseFile, error) {
	if !s.memoWalk {
		return s.walkStoreOnce()
	}
	s.walkMu.Lock()
	defer s.walkMu.Unlock()
	if s.walk == nil {
		files, loose, err := s.walkStoreOnce()
		if err != nil {
			return nil, nil, err
		}
		s.walk = &storeWalk{files: files, loose: loose}
	}
	return s.walk.files, s.walk.loose, nil
}

type storeWalk struct {
	files []fiberFile
	loose []looseFile
}

func (s *Storage) walkStoreOnce() ([]fiberFile, []looseFile, error) {
	// Resolve symlinks on the root so WalkDir descends into symlinked .felt/ dirs.
	rootResolved, err := filepath.EvalSymlinks(s.root)
	if err != nil {
		return nil, nil, fmt.Errorf("resolving .felt path: %w", err)
	}
	var files []fiberFile
	var loose []looseFile
	visited := map[string]struct{}{}

	// walkFn walks one tier of the felt tree, recursing through any symlinked
	// subdirectory. `walkBase` is the absolute, symlinks-resolved root of this
	// tier; ids are computed relative to it so they stay clean even when the
	// symlink target lives outside `rootResolved` — the case where a
	// subdirectory of this store is a symlink into a foreign `.felt/`
	// elsewhere on disk (a "mounted" sub-store).
	//
	// `idPrefix` carries the symlink's logical position in the outer tree
	// (e.g. `projects/foo/`), and is prepended to inner-relative ids so
	// they surface in the outer namespace as `projects/foo/<inner>` instead
	// of leaking the resolved absolute path through filepath.Rel as
	// `../../<somewhere>/...`. The convention matches how regular
	// directories work: the path you place a symlink at *is* its name in
	// the outer namespace.
	var walkFn func(walkBase, idPrefix string) error
	// walkDirFn walks a single tier by hand (os.ReadDir + manual recursion)
	// rather than filepath.WalkDir, so it holds each directory's sibling
	// DirEntry list in memory. That list is what fs.WalkDir would have read
	// internally anyway; keeping it lets a fiber's `report.html` sibling be
	// detected by scanning entries already in hand — zero extra syscalls —
	// instead of an os.Stat per fiber.
	var walkDirFn func(dir, walkBaseResolved, idPrefix string) error
	walkDirFn = func(dir, walkBaseResolved, idPrefix string) error {
		entries, err := os.ReadDir(dir)
		if err != nil {
			return err
		}
		hasReportHTML := false
		for _, e := range entries {
			if !e.IsDir() && e.Name() == "report.html" {
				hasReportHTML = true
				break
			}
		}
		for _, d := range entries {
			fullPath := filepath.Join(dir, d.Name())
			// Symlinked subdirectory: capture its logical position relative to
			// walkBaseResolved before resolving, so the recursive walk lifts
			// every inner id back into the outer namespace.
			if d.Type()&os.ModeSymlink != 0 {
				target, err := filepath.EvalSymlinks(fullPath)
				if err != nil {
					continue // skip broken symlinks
				}
				info, err := os.Stat(target)
				if err != nil {
					continue
				}
				if info.IsDir() {
					inner, err := filepath.Rel(walkBaseResolved, fullPath)
					if err != nil {
						continue
					}
					nextPrefix := path.Join(idPrefix, filepath.ToSlash(inner))
					if err := walkFn(target, nextPrefix); err != nil {
						return err
					}
					continue
				}
				// Symlink to a regular file (e.g. a fiber .md symlinked in from
				// elsewhere): fall through to the normal file handling below —
				// filepath.WalkDir used to visit these too, since it doesn't
				// distinguish a symlink-to-file from a real file once resolved.
			}
			if d.IsDir() {
				if err := walkDirFn(fullPath, walkBaseResolved, idPrefix); err != nil {
					return err
				}
				continue
			}
			if !strings.HasSuffix(d.Name(), FileExt) {
				continue
			}
			// A file is named by where it sits in this tier — a symlinked file
			// included, exactly as a symlinked directory is named by where it is
			// placed — then lifted into the outer namespace by the tier's
			// prefix. The walk only descends real directories under the
			// resolved tier root, so the relative path is always clean.
			rel, err := filepath.Rel(walkBaseResolved, fullPath)
			if err != nil {
				return err
			}
			id, entryPoint, ok := fiberIDFromRelativePath(rel)
			if !ok {
				if logical := path.Join(idPrefix, filepath.ToSlash(rel)); !hiddenPath(logical) {
					loose = append(loose, looseFile{path: fullPath, rel: logical, symlink: d.Type()&os.ModeSymlink != 0})
				}
				continue
			}
			if idPrefix != "" {
				id = path.Join(idPrefix, id)
				// Crossing a symlink into a sub-store means this file is never
				// the *outer* entry-point fiber — the entry-point shape only
				// applies at the root the user is asking about.
				entryPoint = false
			}
			var reportPath string
			if hasReportHTML {
				reportPath = filepath.Join(dir, "report.html")
			}
			files = append(files, fiberFile{id: id, path: fullPath, entryPoint: entryPoint, reportPath: reportPath})
		}
		return nil
	}
	walkFn = func(walkBase, idPrefix string) error {
		walkBaseResolved, err := filepath.EvalSymlinks(walkBase)
		if err != nil {
			return nil // skip unresolvable roots
		}
		if _, seen := visited[walkBaseResolved]; seen {
			return nil
		}
		visited[walkBaseResolved] = struct{}{}
		return walkDirFn(walkBaseResolved, walkBaseResolved, idPrefix)
	}
	if err := walkFn(rootResolved, ""); err != nil {
		return nil, nil, fmt.Errorf("walking .felt directory: %w", err)
	}
	return files, loose, nil
}

// fiberIDFromRelativePath returns (id, entryPoint, ok). entryPoint is true
// when the file is a bare `<slug>.md` at the `.felt/` root — the shape the
// project-level root fiber takes.
func fiberIDFromRelativePath(rel string) (string, bool, bool) {
	rel = filepath.Clean(rel)
	dir := filepath.Dir(rel)
	base := strings.TrimSuffix(filepath.Base(rel), FileExt)
	if dir == "." {
		return base, true, true
	}
	if filepath.Base(dir) != base {
		return "", false, false
	}
	return filepath.ToSlash(dir), false, true
}

// ParentPath returns the parent fiber ID of id, or "" when id names a
// top-level fiber. Fiber IDs are clean, slash-separated and relative, so a
// rooted or empty input has no parent to speak of and degrades to "" rather
// than to "/" — the one answer no fiber ID can be.
func ParentPath(id string) string {
	clean := path.Clean(filepath.ToSlash(id))
	parent := path.Dir(clean)
	if parent == "." || parent == "/" {
		return ""
	}
	return parent
}

// RolesNamespace is the top-level directory that holds role profiles
// (roles/<role>) and their collaborators (roles/<role>/<collaborator>).
const RolesNamespace = "roles"

// NamespaceExists reports whether dir names an existing fiber or a directory
// that holds one — the places a new or moved fiber can land exactly as spelled.
func NamespaceExists(dir string, ids []string) bool {
	if dir == "" {
		return false
	}
	return slices.ContainsFunc(ids, func(id string) bool {
		return id == dir || strings.HasPrefix(id, dir+"/")
	})
}

// ResolveAddPath disambiguates a new fiber's slug-path against the existing
// tree. When the leading segment of slug matches the basename of an existing
// fiber, the slug is rewritten so the new fiber lands under that fiber's
// parent — preventing silent top-level creation when the user meant to nest
// below a fiber that already lives deep in the tree.
//
// Resolution rules:
//   - Single-segment slugs (no `/`) are never resolved; top-level creation is
//     unambiguous in intent.
//   - A slug whose parent already exists as a directory in the tree — a
//     fiber, or a namespace directory such as roles/ that holds fibers without
//     a fiber of its own — is placed exactly as spelled; a basename match
//     elsewhere never overrides a path that exists. Slugs under RolesNamespace
//     are always placed as spelled: that namespace is fixed at the top level.
//   - If no existing fiber has a basename equal to the leading segment, the
//     slug is returned unchanged.
//   - If exactly one existing fiber matches, the new path is `<parent>/<slug>`,
//     and rewritten is true so the caller can inform the user.
//   - If the slug already corresponds to one of the candidate placements
//     (typically because the user passed a fully-qualified path), it's
//     returned as-is with rewritten=false — fully-qualified callers get no
//     surprise rewrite and no info chatter.
//   - If multiple candidates resolve to distinct paths, the function returns
//     an ambiguity error listing each candidate path; the caller must
//     fully-qualify the slug or opt into top-level placement.
func ResolveAddPath(slug string, existingIDs []string) (resolved string, rewritten bool, err error) {
	slug = path.Clean(strings.TrimSpace(slug))
	if !strings.Contains(slug, "/") {
		return slug, false, nil
	}
	leading := slug[:strings.Index(slug, "/")]
	if leading == RolesNamespace || NamespaceExists(ParentPath(slug), existingIDs) {
		return slug, false, nil
	}

	// Candidate parents: each existing fiber whose basename matches the
	// leading segment contributes its parent directory. Parents are
	// deduplicated because two fibers can't share the same id, but two
	// fibers can share a basename in different subtrees.
	var candidates []string
	seenParents := map[string]struct{}{}
	for _, id := range existingIDs {
		if path.Base(id) != leading {
			continue
		}
		parent := ParentPath(id)
		if _, ok := seenParents[parent]; ok {
			continue
		}
		seenParents[parent] = struct{}{}
		var resolvedPath string
		if parent == "" {
			resolvedPath = slug
		} else {
			resolvedPath = parent + "/" + slug
		}
		candidates = append(candidates, resolvedPath)
	}

	if len(candidates) == 0 {
		return slug, false, nil
	}

	// If the user's input already matches one of the candidate placements
	// (e.g. they passed a fully-qualified path or top-level was the right
	// answer), use it as-is — no rewrite, no info chatter.
	if slices.Contains(candidates, slug) {
		return slug, false, nil
	}

	if len(candidates) == 1 {
		return candidates[0], true, nil
	}

	// Ambiguous: stable-sorted candidate list for a deterministic error.
	sort.Strings(candidates)
	return "", false, fmt.Errorf(
		"%q could resolve to multiple existing locations:\n  %s\npass a fully-qualified path or --top-level to disambiguate",
		slug,
		strings.Join(candidates, "\n  "),
	)
}

// ResolveScopedIDIn resolves query by walking up from scopeID like lexical
// scope, with knowledge of the enclosing store for callers that have a *Storage
// in hand (see Storage.ExternalRefs). A nil external is the top-level-store
// case.
func ResolveScopedIDIn(ids []string, scopeID, query string, external *ExternalRefs) (string, error) {
	return newScopedIDResolverIn(ids, external).Resolve(scopeID, query)
}

type scopedIDResolver struct {
	external *ExternalRefs
	// strayAt, when set, names the stray fiber file an id would be (see
	// Storage.strayAt), so a query naming one stops there.
	strayAt      func(id string) (rel string, ok bool)
	ids          []string
	exact        map[string]struct{}
	parentSorted map[string][]scopedIDEntry
	byBase       map[string][]string
}

type scopedIDEntry struct {
	base string
	id   string
}

func newScopedIDResolverIn(ids []string, external *ExternalRefs) *scopedIDResolver {
	resolver := &scopedIDResolver{
		external:     external,
		ids:          make([]string, 0, len(ids)),
		exact:        make(map[string]struct{}, len(ids)),
		parentSorted: map[string][]scopedIDEntry{},
		byBase:       map[string][]string{},
	}
	for _, id := range ids {
		cleanID := path.Clean(id)
		resolver.ids = append(resolver.ids, cleanID)
		resolver.exact[cleanID] = struct{}{}

		parent := ParentPath(cleanID)
		base := path.Base(cleanID)
		resolver.parentSorted[parent] = append(resolver.parentSorted[parent], scopedIDEntry{base: base, id: cleanID})
		resolver.byBase[base] = append(resolver.byBase[base], cleanID)
	}
	sort.Strings(resolver.ids)
	for parent, entries := range resolver.parentSorted {
		sort.Slice(entries, func(i, j int) bool {
			if entries[i].base != entries[j].base {
				return entries[i].base < entries[j].base
			}
			return entries[i].id < entries[j].id
		})
		resolver.parentSorted[parent] = entries
	}
	return resolver
}

// resolution names the rule that answered a lookup.
type resolution int

const (
	// resolvedExact: the exact id, or the query joined to the citing fiber's
	// scope or one of its ancestors — spelled locally or with this view's
	// prefix in the enclosing store's namespace.
	resolvedExact resolution = iota
	// resolvedByTail: the query is the whole-segment tail of exactly one id
	// — a unique bare slug, or a correct partial path.
	resolvedByTail
	// resolvedByPrefix: the query is a string prefix of exactly one id in
	// scope, not a whole segment of it.
	resolvedByPrefix
	// resolvedBySlug: the stale-path rescue. The query's path matched
	// nothing and only its final segment was kept, so the rest of what it
	// wrote is contradicted by where the fiber actually lives.
	resolvedBySlug
)

// guess reports whether the rule guessed: kept less of the query than it
// wrote. A command that deletes or moves never acts on a guess.
func (v resolution) guess() bool {
	return v == resolvedByPrefix || v == resolvedBySlug
}

func (r *scopedIDResolver) Resolve(scopeID, query string) (string, error) {
	id, _, err := r.resolve(scopeID, query)
	return id, err
}

// resolve is Resolve, also reporting which rule answered.
//
// Resolution runs in tiers, and every exact answer — anywhere in the store
// this view is a lens on — outranks every inferred one. A query that spells
// out a real id means that id, even when a local id happens to begin with the
// same letters: `other/deep` names the enclosing store's `other/deep`, never
// this view's `other/deepx`.
//
//  1. Exact: the id itself or the query joined to a scope in the lexical
//     chain, in this store, then spelled with this view's own prefix, then
//     the id in the enclosing store written from its root (stray files count
//     as exact: a path naming one means that file).
//  2. Inferred locally: prefix completion along the scope chain, then a
//     unique whole-segment tail.
//  3. Inferred by the enclosing store's own slug, suffix and prefix rules.
//  4. The basename rescue for a stale path.
func (r *scopedIDResolver) resolve(scopeID, query string) (string, resolution, error) {
	query = cleanLookupQuery(query)
	scopeID = cleanLookupScope(scopeID)
	if query == "" {
		return "", resolvedExact, fmt.Errorf("no fiber found matching %q", query)
	}

	if id, via, ok, err := r.resolveByPath(scopeID, query); ok || err != nil {
		return id, via, err
	}

	// Nothing in this store answers to the query. Before the basename rescue
	// below gets to guess, ask the enclosing store whether ITS inference
	// rules reach a fiber out there: a path that names a real fiber THERE is
	// not a stale local path, it is a link out of this view. This walks the
	// enclosing store's id list — once, memoized, and only on a local miss —
	// so a partial foreign path resolves whether or not its slug happens to
	// collide with a local one.
	//
	// The two rescues overlap, and this order resolves the overlap in the
	// enclosing store's favour. A stale local path whose slug is unique here
	// AND which the enclosing store INFERS — by its own suffix and basename
	// rules, over a far larger id set — is reported as external instead of
	// being repaired into the local fiber. The reader loses that repair, so
	// `felt check` reports it: an info issue naming both candidates, emitted
	// on the inferred branch only (see checkRelationshipIntegrity). The trade
	// is deliberate: a wrong redirect sends a reader one command away
	// (`felt -C ...`), while the misresolution it replaces silently answered
	// with the wrong fiber — and `felt rm` and `felt nest` act on that answer.
	if id, via, ok := r.external.Lookup(scopeID, query); ok {
		return "", resolvedExact, r.external.err(query, id, true, via != resolvedExact)
	}

	// Last resort: the query's final segment names exactly one fiber. This is
	// the rescue for a link whose PATH has gone stale — `felt nest` moves a
	// fiber and every wikilink written against the old path still points at the
	// right slug — and the store leans on it heavily (removing it turns some
	// five hundred healthy loom links into broken ones). It is also the step
	// that misreads a foreign path as a local slug, which is why an id known to
	// the enclosing store is refused above before ever reaching here.
	//
	// A one-segment query never lands here — it is its own tail, so the
	// unique-tail fallback already answered it — which makes every rescue a
	// written path that turned out wrong. `felt check` warns on each one.
	if ids := r.byBase[path.Base(query)]; len(ids) == 1 {
		return ids[0], resolvedBySlug, nil
	}

	return "", resolvedExact, fmt.Errorf("no fiber found matching %q", query)
}

// ResolvePath is the answer a reference's PATH gives, as opposed to the one
// its slug gives: tiers 1 and 2 of resolve, the steps it takes before it asks
// the enclosing store to infer or falls back to the basename rescue. A query
// resolve answers with resolvedBySlug is exactly one ResolvePath does not
// answer: a stale path held up only by its final segment. A path that names a
// fiber in the enclosing store answers nothing here either — it is a link out
// of this view, and a move inside the view leaves it alone.
func (r *scopedIDResolver) ResolvePath(scopeID, query string) (string, bool) {
	query = cleanLookupQuery(query)
	scopeID = cleanLookupScope(scopeID)
	if query == "" {
		return "", false
	}
	id, _, ok, err := r.resolveByPath(scopeID, query)
	return id, ok && err == nil
}

// resolveByPath is resolve's tiers 1 and 2: every exact answer, then local
// inference. ok is false with a nil error when nothing matched; a non-nil
// error is a hard stop (a stray file, an ambiguity, an id that lives in the
// enclosing store), not an invitation to try the fallbacks in resolve.
func (r *scopedIDResolver) resolveByPath(scopeID, query string) (string, resolution, bool, error) {
	if id, ok, err := r.exactInStore(scopeID, query); ok || err != nil {
		return id, resolvedExact, ok, err
	}

	// A target spelled from the enclosing store's namespace but pointing back
	// into this one (`ai-futures/felt/debug`) names a LOCAL fiber. It is tried
	// only after the query's own spelling, so a local fiber whose id
	// genuinely begins with this store's own prefix still answers to it — and
	// a miss keeps the query the caller typed in its error.
	local, localized := r.external.Localize(query)
	if localized {
		if id, ok, err := r.exactInStore(scopeID, local); ok || err != nil {
			return id, resolvedExact, ok, err
		}
	}

	// A path naming a stray fiber file in the enclosing store means that
	// file; the enclosing store's own slug and suffix rules must not answer
	// it with a same-named fiber elsewhere.
	if rel, ok := r.external.strayAt(scopeID, query); ok {
		return "", resolvedExact, false, strayHintError(fmt.Errorf("no fiber found matching %q", query), rel)
	}

	// A query that is a fiber's id in the enclosing store, written out from
	// its root, is a link out of this view. That is how a foreign id is
	// normally written (it is what `felt ls` prints and what a user copies),
	// and it is what lets `felt rm ai-futures/portolan/debug` reach the fiber
	// it names. A stat pair, memoized — no walk. A spelling relative to the
	// citing fiber's scopes out there is the enclosing store's inference,
	// asked by resolve after this store's own.
	if id, ok := r.external.LookupPath(query); ok {
		return "", resolvedExact, false, r.external.err(query, id, false, false)
	}

	if id, via, ok, err := r.inferInStore(scopeID, query); ok || err != nil {
		return id, via, ok, err
	}
	if localized {
		if id, via, ok, _ := r.inferInStore(scopeID, local); ok {
			return id, via, true, nil
		}
	}
	return "", resolvedExact, false, nil
}

// exactInStore answers a query that names an id in this store outright: the
// id itself, or the query joined to the citing fiber's scope or one of its
// ancestors, innermost first. A candidate naming a stray fiber file is a hard
// stop — that file is what the query means, and no looser rule may answer it
// with some other fiber.
func (r *scopedIDResolver) exactInStore(scopeID, query string) (string, bool, error) {
	if _, ok := r.exact[query]; ok {
		return query, true, nil
	}
	for _, scope := range scopeChain(scopeID) {
		candidate := scopedQuery(scope, query)
		if _, ok := r.exact[candidate]; ok {
			return candidate, true, nil
		}
		if r.strayAt != nil {
			if rel, ok := r.strayAt(candidate); ok {
				return "", false, strayHintError(fmt.Errorf("no fiber found matching %q", query), rel)
			}
		}
	}
	return "", false, nil
}

// inferInStore completes a query no id in this store matches exactly: a
// string prefix of exactly one id along the scope chain (a segmented query
// completes as a path, a bare one as a sibling's basename), then the
// whole-segment tail of exactly one id anywhere in the store.
func (r *scopedIDResolver) inferInStore(scopeID, query string) (string, resolution, bool, error) {
	segmented := strings.Contains(query, "/")
	for _, scope := range scopeChain(scopeID) {
		var matches []string
		if segmented {
			matches = r.prefixMatches(scopedQuery(scope, query))
		} else {
			matches = r.basenamePrefixMatches(scope, query)
		}
		switch len(matches) {
		case 0:
			continue
		case 1:
			return matches[0], resolvedByPrefix, true, nil
		default:
			return "", resolvedExact, false, fmt.Errorf("ambiguous ID %q in scope %q matches: %s", query, displayScope(scope), strings.Join(matches, ", "))
		}
	}

	// Global fallback: when scope-relative resolution finds nothing, a query
	// that names the TAIL of exactly one id anywhere in the store resolves to
	// it. This lets a globally-unique slug be referenced from any scope
	// (including across projects) without a full path, and is scope-independent
	// so the same link resolves from the monorepo and a substore.
	if match, ok := r.uniqueSuffixMatch(query); ok {
		return match, resolvedByTail, true, nil
	}

	return "", resolvedExact, false, nil
}

// uniqueSuffixMatch resolves a query naming the tail of exactly one id.
//
// The match must land on a SEGMENT boundary, and the whole query has to
// participate — which is the correction of the first cut, where the fallback
// took `path.Base(query)` and asked only whether that one word was unique.
// Everything before the last slash was discarded, so a link written out in
// full to a fiber in ANOTHER store — [[ai-futures/portolan/debug]] — quietly
// became a link to whatever local fiber happened to be called `debug`. In the
// felt project's own store that was the fiber doing the linking: it listed
// itself among its references, and `felt check` called it healthy.
//
// A path that fails here is a path with no home in this store, and saying so
// is the honest answer. The bare-slug case is unchanged: a one-segment query
// is its own tail.
func (r *scopedIDResolver) uniqueSuffixMatch(query string) (string, bool) {
	// Any id ending in `query` ends in its basename, so the basename bucket is
	// the candidate set — the loop only has to reject the near misses.
	suffix := "/" + query
	var match string
	found := 0
	for _, id := range r.byBase[path.Base(query)] {
		if id != query && !strings.HasSuffix(id, suffix) {
			continue
		}
		match = id
		found++
	}
	return match, found == 1
}

func (r *scopedIDResolver) prefixMatches(candidate string) []string {
	start := sort.SearchStrings(r.ids, candidate)
	var matches []string
	for _, id := range r.ids[start:] {
		if id != candidate && !strings.HasPrefix(id, candidate) {
			break
		}
		matches = append(matches, id)
	}
	return matches
}

func (r *scopedIDResolver) basenamePrefixMatches(scopeID, query string) []string {
	entries := r.parentSorted[scopeID]
	start := sort.Search(len(entries), func(i int) bool {
		return entries[i].base >= query
	})
	var matches []string
	for _, entry := range entries[start:] {
		if !strings.HasPrefix(entry.base, query) {
			break
		}
		matches = append(matches, entry.id)
	}
	return matches
}

func cleanLookupQuery(query string) string {
	query = strings.TrimSpace(query)
	if query == "" {
		return ""
	}
	query = path.Clean(query)
	if query == "." {
		return ""
	}
	return query
}

func cleanLookupScope(scopeID string) string {
	scopeID = strings.TrimSpace(scopeID)
	if scopeID == "" {
		return ""
	}
	scopeID = path.Clean(scopeID)
	if scopeID == "." {
		return ""
	}
	return scopeID
}

func scopeChain(scopeID string) []string {
	scopeID = cleanLookupScope(scopeID)
	if scopeID == "" {
		return []string{""}
	}
	var scopes []string
	for {
		scopes = append(scopes, scopeID)
		parent := ParentPath(scopeID)
		if parent == "" {
			break
		}
		scopeID = parent
	}
	return append(scopes, "")
}

func scopedQuery(scopeID, query string) string {
	if scopeID == "" {
		return query
	}
	return path.Join(scopeID, query)
}

func displayScope(scopeID string) string {
	if scopeID == "" {
		return "."
	}
	return scopeID
}

// FindProjectRoot walks up from the current directory to find a .felt directory.
func FindProjectRoot() (string, error) {
	dir, err := os.Getwd()
	if err != nil {
		return "", fmt.Errorf("getting working directory: %w", err)
	}

	for {
		feltDir := filepath.Join(dir, DirName)
		if info, err := os.Stat(feltDir); err == nil && info.IsDir() {
			return dir, nil
		}

		parent := filepath.Dir(dir)
		if parent == dir {
			// Reached filesystem root
			return "", fmt.Errorf("no .felt directory found")
		}
		dir = parent
	}
}

func readMetadataFile(path, id string) (*Felt, error) {
	frontmatter, err := readFrontmatterFile(path)
	if err != nil {
		return nil, err
	}
	return parseFrontmatter(id, frontmatter)
}

// readFrontmatterFile returns the frontmatter SplitFrontmatter would, reading
// only as far as the closing delimiter: a fiber's metadata costs its
// frontmatter, not its body, and a large markdown file costs one line when it
// has no frontmatter at all.
func readFrontmatterFile(path string) ([]byte, error) {
	file, err := os.Open(path)
	if err != nil {
		return nil, err
	}
	defer file.Close()
	r := bufio.NewReader(file)

	first, err := r.ReadBytes('\n')
	if err != nil && err != io.EOF {
		return nil, err
	}
	if len(first) == 0 {
		return nil, fmt.Errorf("empty file")
	}
	if !isDocumentDelimiterLine(bytes.TrimSuffix(first, []byte("\n"))) {
		return nil, fmt.Errorf("file must start with ---")
	}
	var frontmatter []byte
	for err == nil {
		var line []byte
		line, err = r.ReadBytes('\n')
		if err != nil && err != io.EOF {
			return nil, err
		}
		if len(line) > 0 && isDocumentDelimiterLine(bytes.TrimSuffix(line, []byte("\n"))) {
			return frontmatter, nil
		}
		frontmatter = append(frontmatter, line...)
	}
	return nil, fmt.Errorf("unclosed frontmatter (missing closing ---)")
}

func fileFrontmatterHasTopLevelFields(path string, fields []string) (bool, error) {
	frontmatter, err := readFrontmatterFile(path)
	if err != nil {
		return false, err
	}
	return frontmatterHasTopLevelFields(frontmatter, fields), nil
}

func frontmatterHasTopLevelFields(frontmatter []byte, fields []string) bool {
	if len(fields) == 0 {
		return true
	}

	remaining := make(map[string]struct{}, len(fields))
	for _, field := range fields {
		remaining[field] = struct{}{}
	}

	mapping, err := frontmatterMappingNode(frontmatter)
	if err != nil || mapping == nil {
		return false
	}
	for i := 0; i+1 < len(mapping.Content); i += 2 {
		delete(remaining, mapping.Content[i].Value)
		if len(remaining) == 0 {
			return true
		}
	}
	return false
}

func (s *Storage) nextAvailableMigrationID(baseID string, reserved map[string]struct{}) (string, error) {
	for n := 1; ; n++ {
		candidate := baseID
		if n > 1 {
			candidate = fmt.Sprintf("%s-%d", baseID, n)
		}
		if _, ok := reserved[candidate]; ok {
			continue
		}
		if _, err := os.Stat(s.Path(candidate)); err == nil {
			continue
		} else if !os.IsNotExist(err) {
			return "", fmt.Errorf("checking id %s: %w", candidate, err)
		}
		return candidate, nil
	}
}

func remapIDPrefix(id, oldPrefix, newPrefix string) (string, bool) {
	id = path.Clean(id)
	oldPrefix = path.Clean(oldPrefix)
	newPrefix = path.Clean(newPrefix)
	if id == oldPrefix {
		return newPrefix, true
	}
	if strings.HasPrefix(id, oldPrefix+"/") {
		return newPrefix + strings.TrimPrefix(id, oldPrefix), true
	}
	return id, false
}
