package felt

import (
	"bytes"
	"errors"
	"fmt"
	"os"
	"path"
	"path/filepath"
	"slices"
	"sort"
	"strings"
	"sync"
	"syscall"

	"gopkg.in/yaml.v3"
)

const (
	// DirName is the directory where felt files are stored.
	DirName = ".felt"
	// FileExt is the extension for felt files.
	FileExt = ".md"
	// LegacyMystConfigName is a MyST project file older felt versions wrote
	// into the store root. felt no longer creates one; the readers skip it so
	// a store that still carries one is read cleanly.
	LegacyMystConfigName = "myst.yml"
	// GitignoreName is the felt store ignore file generated at init time.
	GitignoreName = ".gitignore"
)

const defaultGitignore = `# Generated by felt — local fiber-write locks
*.md.lock
`

// Storage handles reading and writing felt files.
type Storage struct {
	root string // Path to .felt directory

	// quietWalk silences the per-file "failed to parse" and iCloud-eviction
	// warnings the listing walk prints to stderr. Those warnings exist because
	// the walk skips what it cannot read: every other command would otherwise
	// lose a fiber without saying so. `felt check` reports the same failures
	// properly, as counted issues (see CheckParseability), so it turns them off
	// rather than printing each one twice.
	quietWalk bool

	enclosingOnce sync.Once
	external      *ExternalRefs
}

// ErrExternalReference reports a query that names a real fiber in the
// ENCLOSING store rather than this one. It is a resolution failure — the
// fiber is not in this VIEW — but a distinguishable one, and what callers do
// with it differs: `felt check` stays quiet (the link is healthy, the view is
// narrow), while a command acting on user input reaches across and operates
// on the fiber where it lives.
//
// The sentinel exists to stop the basename rescue from stealing foreign paths
// and to tell check "not broken". It is not a fence around the enclosing
// store, and the error text deliberately suggests no command: the caller
// knows which verb the user typed, this package does not.
var ErrExternalReference = errors.New("lives in the enclosing felt store")

// ExternalReference is the resolution failure ErrExternalReference names,
// carrying enough to act on: the query as typed, the id it has in the
// enclosing store, and where that store is.
// Inferred distinguishes the two ways a query reaches out there. False means
// the query named the fiber's path exactly, from the enclosing store's root —
// someone deliberately wrote the full outer id, and there is nothing to
// remark on. True means the enclosing store's own resolver INFERRED the
// target by its scope, suffix, and basename rules; that is the case that can
// quietly outrank a local rescue, and the only one worth reporting.
type ExternalReference struct {
	Query      string
	ID         string
	Root       string // the enclosing .felt directory
	ProjectDir string // its project root — what `felt -C` takes
	Inferred   bool
}

func (e *ExternalReference) Error() string {
	return fmt.Sprintf("%q %s as %s (%s)", e.Query, ErrExternalReference, e.ID, e.Root)
}

func (e *ExternalReference) Unwrap() error { return ErrExternalReference }

// AsExternalReference extracts the external-reference detail from an error,
// for a caller that wants to act on the fiber rather than report the failure.
func AsExternalReference(err error) (*ExternalReference, bool) {
	var ref *ExternalReference
	if errors.As(err, &ref) {
		return ref, true
	}
	return nil, false
}

// EnclosingStore reports the store this one is mounted inside, if any.
//
// A substore is a `.felt/` that is a symlink into a subdirectory of another
// `.felt/` — the project store at `<project>/.felt` pointing into the loom at
// `~/loom/.felt/<prefix>`. root is the enclosing `.felt/` directory, prefix is
// this store's slash-separated position inside it, and ok is false for an
// ordinary top-level store.
//
// s.root is the unresolved path (the symlink itself), so the answer comes
// from EvalSymlinks plus an ancestor walk looking for a `.felt` directory.
// The result is memoized: resolution consults it once per query.
func (s *Storage) EnclosingStore() (root string, prefix string, ok bool) {
	s.enclosingOnce.Do(func() {
		resolved, err := filepath.EvalSymlinks(s.root)
		if err != nil {
			return
		}
		for dir := filepath.Dir(resolved); ; dir = filepath.Dir(dir) {
			if filepath.Base(dir) == DirName && looksLikeStore(dir) {
				rel, err := filepath.Rel(dir, resolved)
				if err != nil || rel == "." || rel == ".." || strings.HasPrefix(rel, ".."+string(filepath.Separator)) {
					return
				}
				s.external = &ExternalRefs{root: dir, prefix: filepath.ToSlash(rel), cache: map[string]string{}}
				return
			}
			if parent := filepath.Dir(dir); parent == dir {
				return
			}
		}
	})
	return s.external.Root(), s.external.Prefix(), s.external != nil
}

// ExternalRefs returns the external-reference oracle for this store, or nil
// when the store is top-level (nothing is external to a store that encloses
// nothing). The nil value is usable — every method is nil-safe — so callers
// pass it along without branching. One instance per Storage, so its stat
// answers are memoized across calls.
func (s *Storage) ExternalRefs() *ExternalRefs {
	s.EnclosingStore()
	return s.external
}

// looksLikeStore reports whether dir holds felt content, so that a directory
// that is merely NAMED `.felt` — a repository checked out inside someone
// else's store, a stray fixture — is not mistaken for the store this one is
// mounted in. One ReadDir: a fiber is either a bare `<slug>.md` or a
// `<slug>/<slug>.md`, and one of either is enough.
func looksLikeStore(dir string) bool {
	entries, err := os.ReadDir(dir)
	if err != nil {
		return false
	}
	for _, entry := range entries {
		name := entry.Name()
		if !entry.IsDir() {
			if name != LegacyMystConfigName && strings.HasSuffix(name, FileExt) {
				return true
			}
			continue
		}
		if info, err := os.Stat(filepath.Join(dir, name, name+FileExt)); err == nil && !info.IsDir() {
			return true
		}
	}
	return false
}

// ExternalRefs answers, for a substore, whether a reference target names a
// fiber that lives elsewhere in the enclosing store. Two questions, both of
// which change how a query should be read from inside the substore:
//
//   - Localize: a target written with this store's own prefix
//     (`ai-futures/felt/debug`) is a LOCAL fiber spelled from the outer
//     namespace; strip the prefix and resolve the remainder in-store.
//   - Resolves: a target the ENCLOSING store resolves to a fiber outside this
//     store's prefix is genuinely elsewhere, and must not be salvaged by the
//     basename fallback into whatever local fiber shares its slug.
type ExternalRefs struct {
	root   string
	prefix string

	once     sync.Once
	resolver *scopedIDResolver

	mu    sync.Mutex
	cache map[string]string // query -> its id out there, "" for "not out there"
}

// Root is the enclosing `.felt/` directory.
func (x *ExternalRefs) Root() string {
	if x == nil {
		return ""
	}
	return x.root
}

// Prefix is this store's position inside the enclosing store.
func (x *ExternalRefs) Prefix() string {
	if x == nil {
		return ""
	}
	return x.prefix
}

// ProjectDir is the directory to hand `felt -C` to open the enclosing store.
func (x *ExternalRefs) ProjectDir() string {
	if x == nil {
		return ""
	}
	return filepath.Dir(x.root)
}

// Localize strips this store's own prefix from a query, reporting whether it
// applied.
func (x *ExternalRefs) Localize(query string) (string, bool) {
	if x == nil || x.prefix == "" {
		return query, false
	}
	rest, ok := strings.CutPrefix(query, x.prefix+"/")
	if !ok || rest == "" {
		return query, false
	}
	return rest, true
}

// LookupPath is the cheap half of the external check: query names a fiber in
// the enclosing store when `<root>/<query>/<slug>.md` is there — the canonical
// on-disk shape of a fiber. Two syscalls, memoized, no walk, which is why it
// runs on every miss rather than behind the probe gate.
//
// It answers only for ids written out in full from the enclosing store's root.
// Partial paths and bare slugs that live deeper are the walk's business.
func (x *ExternalRefs) LookupPath(query string) (string, bool) {
	if x == nil || query == "" || strings.HasPrefix(query, "/") || strings.HasPrefix(query, "..") {
		return "", false
	}
	if query == x.prefix || strings.HasPrefix(query, x.prefix+"/") {
		return "", false
	}
	key := "path\x00" + query
	x.mu.Lock()
	id, seen := x.cache[key]
	x.mu.Unlock()
	if seen {
		return id, id != ""
	}

	id = ""
	file := filepath.Join(x.root, filepath.FromSlash(query), path.Base(query)+FileExt)
	if info, err := os.Stat(file); err == nil && !info.IsDir() {
		id = query
	}
	x.mu.Lock()
	x.cache[key] = id
	x.mu.Unlock()
	return id, id != ""
}

// Lookup reports whether the enclosing store resolves query — from the
// position this store's scope occupies out there — to a fiber outside this
// store's own subtree.
//
// The test is resolution, not file existence, because that is how the links
// were written: `[[gotcha-remote-felt-index-stale-after-gitsync]]` and
// `[[portolan/patterns/switch-to-permission-mode-auto]]` name no path from
// the loom root, and both resolve cleanly from the loom by the same slug and
// suffix rules this resolver applies locally. Asking the enclosing store the
// same question the loom's own `felt check` asks is the only predicate that
// agrees with it.
//
// A hit that lands back inside this store's prefix is NOT external — it is a
// local fiber the enclosing store reached by a path this view spells
// differently — so it falls through to the local fallbacks.
//
// The enclosing store's id list is walked once, lazily: nothing here runs
// until a query has already failed to resolve locally, so a top-level store
// or a substore with clean links never pays for it.
func (x *ExternalRefs) Lookup(scopeID, query string) (string, bool) {
	if x == nil || query == "" {
		return "", false
	}
	key := scopeID + "\x00" + query
	x.mu.Lock()
	found, seen := x.cache[key]
	x.mu.Unlock()
	if seen {
		return found, found != ""
	}

	x.once.Do(func() {
		outer := &Storage{root: x.root}
		files, err := outer.listFiberFiles()
		if err != nil {
			x.resolver = newScopedIDResolverIn(nil, nil)
			return
		}
		ids := make([]string, 0, len(files))
		for _, file := range files {
			ids = append(ids, file.id)
		}
		x.resolver = newScopedIDResolverIn(ids, nil)
	})

	// The citing fiber sits at <prefix>/<scopeID> in the outer namespace;
	// resolving from there is the same lexical walk the enclosing store runs.
	id, err := x.resolver.Resolve(path.Join(x.prefix, scopeID), query)
	if err != nil || id == x.prefix || strings.HasPrefix(id, x.prefix+"/") {
		id = ""
	}

	x.mu.Lock()
	x.cache[key] = id
	x.mu.Unlock()
	return id, id != ""
}

// err builds the resolution failure for an external target: the sentinel, the
// query, and the id it has out there — everything a caller needs to act on
// the fiber where it lives.
func (x *ExternalRefs) err(query, id string, inferred bool) error {
	return &ExternalReference{Query: query, ID: id, Root: x.root, ProjectDir: x.ProjectDir(), Inferred: inferred}
}

type fiberFile struct {
	id         string
	path       string
	entryPoint bool   // bare `.felt/<slug>.md` at the .felt/ root
	reportPath string // sibling report.html, if any (absolute, symlink-resolved dir)
}

type MigrationEntry struct {
	OldID string
	NewID string
}

type MigrationResult struct {
	Entries               []MigrationEntry
	TitleToNameIDs        []string
	RemovedDependsOnIDs   []string
	StrippedMystAnchorIDs []string
}

type IdentityBackfillResult struct {
	AssignedIDs []string
}

// NewStorage creates a storage instance for the given directory.
// The directory should be the project root (containing .felt/).
func NewStorage(projectRoot string) *Storage {
	return &Storage{
		root: filepath.Join(projectRoot, DirName),
	}
}

// Root is this store's `.felt` directory — the path that identifies the store
// a fiber was found in, which a cross-store result has to name.
func (s *Storage) Root() string { return s.root }

// Init creates the .felt directory if it doesn't exist.
func (s *Storage) Init() error {
	if err := os.MkdirAll(s.root, 0755); err != nil {
		return fmt.Errorf("creating .felt directory: %w", err)
	}
	gitignorePath := filepath.Join(s.root, GitignoreName)
	if _, err := os.Stat(gitignorePath); os.IsNotExist(err) {
		if err := os.WriteFile(gitignorePath, []byte(defaultGitignore), 0644); err != nil {
			return fmt.Errorf("writing %s: %w", GitignoreName, err)
		}
	} else if err != nil {
		return fmt.Errorf("checking %s: %w", GitignoreName, err)
	}
	return nil
}

// SilenceWalkWarnings suppresses the listing walk's stderr warnings about
// files it had to skip. Only `felt check` should use it: it reports those same
// files as issues, with an exit code behind them, and printing both would say
// the same thing twice in two different registers.
func (s *Storage) SilenceWalkWarnings() {
	s.quietWalk = true
}

// Exists returns true if the .felt directory exists.
func (s *Storage) Exists() bool {
	info, err := os.Stat(s.root)
	return err == nil && info.IsDir()
}

// Path returns the full path for a felt file. Fibers can take one of two
// on-disk shapes:
//
//   - directory form  `<.felt>/<id>/<slug>.md`   (the standard layout)
//   - bare form       `<.felt>/<dir>/<slug>.md`  (no `<slug>/` nesting)
//
// The bare form occurs at namespace-root boundaries: the file sits directly
// inside a `.felt/` rather than in a `<slug>/` subdirectory. At depth zero
// it is the project-root fiber. At depth greater than zero it appears when
// another felt store is mounted via a symlinked subdirectory — its
// inner-root fiber surfaces in the outer namespace one tier deeper than the
// outer root.
//
// Path prefers the directory form for nested ids. Bare-form `.md` files at
// depth > 0 are usually sidecars (transcripts, notes adjacent to a real
// fiber) and don't carry frontmatter; preferring them would resolve to the
// wrong file. The bare fallback fires only when the directory form is
// missing, which is exactly the symlinked-substore case.
func (s *Storage) Path(id string) string {
	id = filepath.ToSlash(filepath.Clean(id))
	slug := path.Base(id)
	dir := path.Dir(id)
	dirForm := filepath.Join(s.root, filepath.FromSlash(id), slug+FileExt)
	if dir == "." {
		// Top-level: prefer the bare shape `.felt/<slug>.md` when it exists —
		// that's the project-root fiber's canonical layout when this store
		// is mounted into an outer one via a symlink at the parent level.
		// Falls back to the directory form for the standard nested layout.
		bare := filepath.Join(s.root, slug+FileExt)
		if _, err := os.Stat(bare); err == nil {
			return bare
		}
		return dirForm
	}
	// Nested ids: directory form first. The bare-at-parent shape only
	// appears at a symlink boundary into another store; fall through to it
	// when (and only when) the directory form doesn't resolve, so a
	// sidecar `.md` next to a directory-form fiber can't shadow the fiber.
	if _, err := os.Stat(dirForm); err == nil {
		return dirForm
	}
	bare := filepath.Join(s.root, filepath.FromSlash(dir), slug+FileExt)
	if _, err := os.Stat(bare); err == nil {
		return bare
	}
	return dirForm
}

// CheckAvailableID returns an error if the target fiber ID already exists.
func (s *Storage) CheckAvailableID(id string) error {
	id = filepath.ToSlash(filepath.Clean(strings.TrimSpace(id)))
	if id == "." || id == "" {
		return fmt.Errorf("invalid felt id")
	}
	if _, err := os.Stat(s.Path(id)); err == nil {
		return fmt.Errorf("fiber %q already exists", id)
	} else if !os.IsNotExist(err) {
		return fmt.Errorf("checking existing fiber %q: %w", id, err)
	}
	return nil
}

// Write saves a felt to disk.
func (s *Storage) Write(f *Felt) error {
	if f == nil {
		return fmt.Errorf("cannot write nil felt")
	}
	data, err := f.Marshal()
	if err != nil {
		return err
	}

	path := s.Path(f.ID)
	if err := os.MkdirAll(filepath.Dir(path), 0755); err != nil {
		return fmt.Errorf("creating directory %s: %w", filepath.Dir(path), err)
	}
	if err := os.WriteFile(path, data, 0644); err != nil {
		return fmt.Errorf("writing file %s: %w", path, err)
	}
	return nil
}

// Read loads a felt from disk by ID.
func (s *Storage) Read(id string) (*Felt, error) {
	return s.readPathWithMode(s.Path(id), id, ParseFull)
}

// FindMetadataInScope returns the first felt matching the query using lexical
// scoped resolution rooted at scopeID.
func (s *Storage) FindMetadataInScope(scopeID, query string) (*Felt, error) {
	return s.findWithModeAndScope(scopeID, query, ParseMetadataOnly)
}

// FindExistingMetadataInScope resolves only direct on-disk candidates in the
// lexical scope chain. It intentionally does not fall back to walking the whole
// store, so narrow read paths can annotate exact refs without surprise work.
func (s *Storage) FindExistingMetadataInScope(scopeID, query string) (*Felt, bool, error) {
	return s.findExistingPathWithModeAndScope(scopeID, query, ParseMetadataOnly)
}

// readPathWithMode reads a fiber from a known on-disk path. Used by list-time
// callers that already discovered the file via the walk and shouldn't re-derive
// the path from the id (which loses information when ids cross symlink
// boundaries — e.g. an entry-point bare-form fiber inside a symlinked
// sub-store has no recoverable shape from the prefixed id alone).
func (s *Storage) readPathWithMode(path, id string, mode ParseMode) (*Felt, error) {
	// Canonicalize the on-disk path once so every surface (walk-time list and
	// direct single-read) carries the same absolute, symlink-resolved location
	// — the real "where the bytes are". Walk-time paths are already resolved,
	// so EvalSymlinks is a no-op there; the single-read path is computed via
	// s.Path(id) against the (possibly symlinked) store root, so resolving here
	// keeps it from leaking a symlink-traversing path. Reads still use the
	// original `path` (resolved is only what we carry on f.Path); fall back to
	// the original if resolution fails so a transient stat error can't drop the
	// path entirely.
	carriedPath := path
	if resolved, err := filepath.EvalSymlinks(path); err == nil {
		carriedPath = resolved
	}

	var f *Felt
	if mode == ParseMetadataOnly {
		var err error
		if f, err = readMetadataFile(path, id); err != nil {
			return nil, fmt.Errorf("reading file %s: %w", path, err)
		}
	} else {
		data, err := os.ReadFile(path)
		if err != nil {
			return nil, fmt.Errorf("reading file %s: %w", path, err)
		}
		if f, err = ParseWithMode(id, data, mode); err != nil {
			return nil, err
		}
	}
	// Carry the on-disk path so consumers read it instead of
	// reconstructing it from the id.
	f.Path = carriedPath
	return f, nil
}

// Delete removes a felt from disk.
func (s *Storage) Delete(id string) error {
	path := s.Path(id)
	if err := os.Remove(path); err != nil {
		return fmt.Errorf("deleting file %s: %w", path, err)
	}
	return s.pruneEmptyDirs(filepath.Dir(path))
}

// pruneEmptyDirs removes now-empty ancestor directories, walking from startDir
// up toward (but never including) the store root. It stops at the first
// non-empty directory; any other removal error is reported.
func (s *Storage) pruneEmptyDirs(startDir string) error {
	for dir := startDir; dir != s.root; dir = filepath.Dir(dir) {
		err := os.Remove(dir)
		if err == nil {
			continue
		}
		if errors.Is(err, syscall.ENOTEMPTY) {
			break
		}
		return fmt.Errorf("cleaning directory %s: %w", dir, err)
	}
	return nil
}

// MoveSubtree moves a fiber and any nested descendants to a new path, rewriting
// data-flow references across the repository.
func (s *Storage) MoveSubtree(oldID, newID string) error {
	oldID = filepath.ToSlash(filepath.Clean(strings.TrimSpace(oldID)))
	newID = filepath.ToSlash(filepath.Clean(strings.TrimSpace(newID)))
	if oldID == "." || oldID == "" || newID == "." || newID == "" {
		return fmt.Errorf("invalid felt id")
	}
	if oldID == newID {
		return fmt.Errorf("source and destination are the same")
	}
	if strings.HasPrefix(newID, oldID+"/") {
		return fmt.Errorf("cannot move %s into its own subtree %s", oldID, newID)
	}
	if _, err := os.Stat(s.Path(newID)); err == nil {
		return fmt.Errorf("destination %s already exists", newID)
	} else if !os.IsNotExist(err) {
		return fmt.Errorf("checking destination %s: %w", newID, err)
	}

	felts, err := s.List()
	if err != nil {
		return err
	}

	updated := make([]*Felt, 0, len(felts))
	movedAny := false
	for _, f := range felts {
		clone := *f
		if remappedID, ok := remapIDPrefix(clone.ID, oldID, newID); ok {
			clone.ID = remappedID
			movedAny = true
		}
		clone.RewriteDataFlowRefs(func(ref string) (string, bool) {
			return remapDataFlowRef(ref, oldID, newID)
		})
		updated = append(updated, &clone)
	}

	if !movedAny {
		return fmt.Errorf("no felt found at %s", oldID)
	}

	oldRoot := filepath.Join(s.root, filepath.FromSlash(oldID))
	newRoot := filepath.Join(s.root, filepath.FromSlash(newID))
	if _, err := os.Stat(newRoot); err == nil {
		return fmt.Errorf("destination %s already exists", newID)
	} else if !os.IsNotExist(err) {
		return fmt.Errorf("checking destination directory %s: %w", newID, err)
	}
	if err := os.MkdirAll(filepath.Dir(newRoot), 0755); err != nil {
		return fmt.Errorf("creating destination parent %s: %w", filepath.Dir(newRoot), err)
	}
	if err := os.Rename(oldRoot, newRoot); err != nil {
		return fmt.Errorf("moving subtree %s -> %s: %w", oldRoot, newRoot, err)
	}

	for _, f := range updated {
		if err := s.Write(f); err != nil {
			return err
		}
	}
	return s.pruneEmptyDirs(filepath.Dir(oldRoot))
}

// Migrate performs the storage-model normalization pass:
// flat-file fibers become directory fibers, legacy frontmatter `title` fields
// become `name`, and leading MyST anchor lines are stripped from bodies.
func (s *Storage) Migrate(dryRun bool) (*MigrationResult, error) {
	result, err := s.MigrateFlatFiles(dryRun)
	if err != nil {
		return nil, err
	}

	titleIDs, dependsOnIDs, anchorIDs, err := s.NormalizeFiberFiles(dryRun)
	if err != nil {
		return nil, err
	}
	result.TitleToNameIDs = titleIDs
	result.RemovedDependsOnIDs = dependsOnIDs
	result.StrippedMystAnchorIDs = anchorIDs
	return result, nil
}

// MigrateFlatFiles converts legacy top-level flat markdown fibers to
// directory-based fibers with slug IDs, rewriting data-flow references.
func (s *Storage) MigrateFlatFiles(dryRun bool) (*MigrationResult, error) {
	if err := s.Init(); err != nil {
		return nil, err
	}

	entries, err := os.ReadDir(s.root)
	if err != nil {
		return nil, fmt.Errorf("reading .felt directory: %w", err)
	}

	type legacyFiber struct {
		oldID string
		path  string
		felt  *Felt
	}

	var legacy []legacyFiber
	for _, entry := range entries {
		if entry.IsDir() {
			continue
		}
		name := entry.Name()
		if name == LegacyMystConfigName || filepath.Ext(name) != FileExt {
			continue
		}
		oldID := strings.TrimSuffix(name, FileExt)
		data, err := os.ReadFile(filepath.Join(s.root, name))
		if err != nil {
			return nil, fmt.Errorf("reading legacy fiber %s: %w", name, err)
		}
		f, err := Parse(oldID, data)
		if err != nil {
			return nil, fmt.Errorf("parsing legacy fiber %s: %w", name, err)
		}
		legacy = append(legacy, legacyFiber{
			oldID: oldID,
			path:  filepath.Join(s.root, name),
			felt:  f,
		})
	}

	// Exactly one bare root .md is assumed the entry-point fiber and left
	// untouched; with two or more we can't tell entry-point from stray, so all
	// are migrated (to <slug>/<slug>.md form).
	if len(legacy) == 1 {
		return &MigrationResult{}, nil
	}

	result := &MigrationResult{Entries: make([]MigrationEntry, 0, len(legacy))}
	if len(legacy) == 0 {
		return result, nil
	}

	used := map[string]struct{}{}
	for _, f := range legacy {
		baseID, err := GenerateID(f.felt.DisplayName())
		if err != nil {
			return nil, fmt.Errorf("generate slug for %s: %w", f.oldID, err)
		}
		newID, err := s.nextAvailableMigrationID(baseID, used)
		if err != nil {
			return nil, err
		}
		used[newID] = struct{}{}
		result.Entries = append(result.Entries, MigrationEntry{
			OldID: f.oldID,
			NewID: newID,
		})
	}

	slices.SortFunc(result.Entries, func(a, b MigrationEntry) int {
		return strings.Compare(a.OldID, b.OldID)
	})

	if dryRun {
		return result, nil
	}

	idMap := map[string]string{}
	for _, entry := range result.Entries {
		idMap[entry.OldID] = entry.NewID
	}

	for _, item := range legacy {
		f := item.felt
		f.ID = idMap[item.oldID]
		f.RewriteDataFlowRefs(func(ref string) (string, bool) {
			if remappedFrom, ok := remapDataFlowRef(ref, item.oldID, f.ID); ok {
				return remappedFrom, true
			}
			targetFiber, fragment := splitDataFlowRef(ref)
			newTargetID, ok := idMap[targetFiber]
			if !ok {
				return "", false
			}
			if fragment == "" {
				return newTargetID, true
			}
			return newTargetID + "." + fragment, true
		})
		if err := s.Write(f); err != nil {
			return nil, err
		}
	}

	for _, item := range legacy {
		if err := os.Remove(item.path); err != nil {
			return nil, fmt.Errorf("removing legacy fiber %s: %w", item.path, err)
		}
	}

	// Rewrite stale hex-suffixed data-flow refs in pre-existing directory fibers.
	allFibers, err := s.List()
	if err != nil {
		return nil, fmt.Errorf("listing fibers for input rewrite: %w", err)
	}
	for _, f := range allFibers {
		changed := f.RewriteDataFlowRefs(func(ref string) (string, bool) {
			targetFiber, fragment := splitDataFlowRef(ref)
			newID, ok := idMap[targetFiber]
			if !ok {
				return "", false
			}
			if fragment == "" {
				return newID, true
			}
			return newID + "." + fragment, true
		})
		if changed {
			if err := s.Write(f); err != nil {
				return nil, fmt.Errorf("rewriting inputs in %s: %w", f.ID, err)
			}
		}
	}

	return result, nil
}

// NormalizeFiberFiles rewrites legacy per-file format details in-place:
// frontmatter `title` -> `name`, and leading MyST anchor lines in bodies.
func (s *Storage) NormalizeFiberFiles(dryRun bool) ([]string, []string, []string, error) {
	files, err := s.listFiberFiles()
	if err != nil {
		return nil, nil, nil, err
	}

	var titleIDs []string
	var dependsOnIDs []string
	var anchorIDs []string
	for _, file := range files {
		data, err := os.ReadFile(file.path)
		if err != nil {
			return nil, nil, nil, fmt.Errorf("reading fiber %s: %w", file.path, err)
		}

		rewritten, renamedTitle, removedDependsOn, strippedAnchor, err := normalizeFiberFile(file.id, data)
		if err != nil {
			return nil, nil, nil, fmt.Errorf("normalize fiber %s: %w", file.path, err)
		}
		if !renamedTitle && !removedDependsOn && !strippedAnchor {
			continue
		}
		if renamedTitle {
			titleIDs = append(titleIDs, file.id)
		}
		if removedDependsOn {
			dependsOnIDs = append(dependsOnIDs, file.id)
		}
		if strippedAnchor {
			anchorIDs = append(anchorIDs, file.id)
		}
		if dryRun {
			continue
		}
		if err := os.WriteFile(file.path, rewritten, 0644); err != nil {
			return nil, nil, nil, fmt.Errorf("writing normalized fiber %s: %w", file.path, err)
		}
	}

	slices.Sort(titleIDs)
	slices.Sort(dependsOnIDs)
	slices.Sort(anchorIDs)
	return titleIDs, dependsOnIDs, anchorIDs, nil
}

// BackfillIntrinsicIDs assigns an intrinsic ULID to every fiber missing one.
// This is intentionally separate from Migrate: replicas must not run it
// casually, or the same git-synced fiber can split into multiple identities.
func (s *Storage) BackfillIntrinsicIDs(dryRun bool) (*IdentityBackfillResult, error) {
	files, err := s.listFiberFiles()
	if err != nil {
		return nil, err
	}

	result := &IdentityBackfillResult{}
	for _, file := range files {
		data, err := os.ReadFile(file.path)
		if err != nil {
			return nil, fmt.Errorf("reading fiber %s: %w", file.path, err)
		}
		rewritten, changed, err := backfillIntrinsicID(data)
		if err != nil {
			fmt.Fprintf(os.Stderr, "warning: failed to backfill %s: %v\n", file.path, err)
			continue
		}
		if !changed {
			continue
		}
		result.AssignedIDs = append(result.AssignedIDs, file.id)
		if dryRun {
			continue
		}
		if err := os.WriteFile(file.path, rewritten, 0644); err != nil {
			return nil, fmt.Errorf("writing identity-backfilled fiber %s: %w", file.path, err)
		}
	}

	slices.Sort(result.AssignedIDs)
	return result, nil
}

func normalizeFiberFile(id string, content []byte) ([]byte, bool, bool, bool, error) {
	frontmatter, body, err := splitFrontmatter(content, true)
	if err != nil {
		return nil, false, false, false, err
	}

	rewrittenFrontmatter, renamedTitle, removedDependsOn, err := normalizeLegacyFrontmatter(frontmatter)
	if err != nil {
		return nil, false, false, false, err
	}
	rewrittenBody, strippedAnchor := stripLegacyMystAnchor(id, body)
	if !renamedTitle && !removedDependsOn && !strippedAnchor {
		return content, false, false, false, nil
	}

	var out bytes.Buffer
	out.WriteString("---\n")
	out.Write(rewrittenFrontmatter)
	out.WriteString("---\n")
	if rewrittenBody != "" {
		out.WriteString("\n")
		out.WriteString(rewrittenBody)
		if !strings.HasSuffix(rewrittenBody, "\n") {
			out.WriteString("\n")
		}
	}
	return out.Bytes(), renamedTitle, removedDependsOn, strippedAnchor, nil
}

func backfillIntrinsicID(content []byte) ([]byte, bool, error) {
	frontmatter, body, err := splitFrontmatter(content, true)
	if err != nil {
		return nil, false, err
	}

	rewrittenFrontmatter, changed, err := backfillIntrinsicIDFrontmatter(frontmatter)
	if err != nil {
		return nil, false, err
	}
	if !changed {
		return content, false, nil
	}

	var out bytes.Buffer
	out.WriteString("---\n")
	out.Write(rewrittenFrontmatter)
	out.WriteString("---\n")
	if body != "" {
		out.WriteString(body)
	}
	return out.Bytes(), true, nil
}

func backfillIntrinsicIDFrontmatter(frontmatter []byte) ([]byte, bool, error) {
	var node yaml.Node
	if err := yaml.Unmarshal(frontmatter, &node); err != nil {
		return nil, false, fmt.Errorf("parsing YAML frontmatter: %w", err)
	}
	if len(node.Content) == 0 {
		return frontmatter, false, nil
	}

	mapping := node.Content[0]
	if mapping.Kind != yaml.MappingNode {
		return nil, false, fmt.Errorf("frontmatter must be a YAML mapping")
	}

	for i := 0; i+1 < len(mapping.Content); i += 2 {
		if mapping.Content[i].Value == "id" && strings.TrimSpace(mapping.Content[i+1].Value) != "" {
			return frontmatter, false, nil
		}
	}

	idKey := &yaml.Node{Kind: yaml.ScalarNode, Tag: "!!str", Value: "id"}
	idValue := &yaml.Node{Kind: yaml.ScalarNode, Tag: "!!str", Value: NewULID()}
	mapping.Content = append([]*yaml.Node{idKey, idValue}, mapping.Content...)

	rewritten, err := yaml.Marshal(mapping)
	if err != nil {
		return nil, false, fmt.Errorf("marshaling YAML frontmatter: %w", err)
	}
	return rewritten, true, nil
}

// List returns all felts in the storage.
func (s *Storage) List() ([]*Felt, error) {
	return s.listWithMode(ParseFull, false)
}

// ListMetadata returns all felts with frontmatter only.
func (s *Storage) ListMetadata() ([]*Felt, error) {
	return s.listWithMode(ParseMetadataOnly, false)
}

// ListMetadataHavingFrontmatterFields returns metadata for fibers whose raw
// frontmatter contains all requested top-level keys. It is a narrow listing
// path for machine consumers that need only one tool-owned namespace (for
// example, every fiber with a `shuttle:` block) and should not pay a full YAML
// parse for unrelated fibers.
func (s *Storage) ListMetadataHavingFrontmatterFields(fields []string) ([]*Felt, error) {
	return s.listWithModeHavingFrontmatterFields(ParseMetadataOnly, false, fields)
}

// ListMetadataWithModTime returns metadata plus file modification times.
func (s *Storage) ListMetadataWithModTime() ([]*Felt, error) {
	return s.listWithMode(ParseMetadataOnly, true)
}

// ListMetadataWithModTimeHavingFrontmatterFields returns metadata plus file
// modification times for fibers whose raw frontmatter contains all requested
// top-level keys.
func (s *Storage) ListMetadataWithModTimeHavingFrontmatterFields(fields []string) ([]*Felt, error) {
	return s.listWithModeHavingFrontmatterFields(ParseMetadataOnly, true, fields)
}

func (s *Storage) listWithMode(mode ParseMode, includeModTime bool) ([]*Felt, error) {
	return s.listWithModeHavingFrontmatterFields(mode, includeModTime, nil)
}

func (s *Storage) listWithModeHavingFrontmatterFields(mode ParseMode, includeModTime bool, fields []string) ([]*Felt, error) {
	files, err := s.listFiberFiles()
	if err != nil {
		return nil, err
	}

	var felts []*Felt
	evicted := 0 // iCloud-dataless files that couldn't be materialized during the walk
	note := func(p string, err error) {
		if isEvictedFileError(err) {
			evicted++
		} else if !s.quietWalk {
			fmt.Fprintf(os.Stderr, "warning: failed to parse %s: %v\n", p, err)
		}
	}
	for _, file := range files {
		if len(fields) > 0 && mode == ParseMetadataOnly {
			matched, err := fileFrontmatterHasTopLevelFields(file.path, fields)
			if err != nil {
				note(file.path, err)
				continue
			}
			if !matched {
				continue
			}
		}
		f, err := s.readPathWithMode(file.path, file.id, mode)
		if err != nil {
			note(file.path, err)
			continue
		}
		if includeModTime {
			if info, err := os.Stat(file.path); err == nil {
				f.ModifiedAt = info.ModTime()
			}
		}
		f.EntryPoint = file.entryPoint
		f.ReportPath = file.reportPath
		felts = append(felts, f)
	}

	if evicted > 0 && !s.quietWalk {
		fmt.Fprintf(os.Stderr, "warning: %d file(s) not materialized (iCloud) under %s; run `brctl download` or open them in Files to hydrate\n", evicted, s.root)
	}

	return felts, nil
}

// isEvictedFileError reports whether err is the failure signature of an
// iCloud-dataless file — one whose metadata is present but whose contents
// haven't been downloaded locally. Reading such a file returns EDEADLK
// ("resource deadlock avoided") on macOS as the CloudDocs daemon declines to
// fault it in synchronously. We match the errno directly (portable via
// syscall) and fall back to a conservative string match so the same eviction
// signature is recognized even when wrapped without an errno.
func isEvictedFileError(err error) bool {
	if err == nil {
		return false
	}
	if errors.Is(err, syscall.EDEADLK) {
		return true
	}
	return strings.Contains(err.Error(), "resource deadlock avoided")
}

// FindInScope returns the first felt matching the query using lexical scoped
// resolution rooted at scopeID.
func (s *Storage) FindInScope(scopeID, query string) (*Felt, error) {
	return s.findWithModeAndScope(scopeID, query, ParseFull)
}

// findWithModeAndScope is the single fiber-resolution implementation behind
// FindInScope / FindMetadataInScope / FindExistingMetadataInScope: it tries
// direct on-disk scope-chain candidates first, then falls back to a full-store
// scan with slug and (UID-shaped) exact-UID matching.
func (s *Storage) findWithModeAndScope(scopeID, query string, mode ParseMode) (*Felt, error) {
	if f, ok, err := s.findExistingPathWithModeAndScope(scopeID, query, mode); ok || err != nil {
		return f, err
	}

	files, err := s.listFiberFiles()
	if err != nil {
		return nil, err
	}

	query = cleanLookupQuery(query)
	scopeID = cleanLookupScope(scopeID)

	pathByID := make(map[string]string, len(files))
	ids := make([]string, 0, len(files))
	for _, file := range files {
		pathByID[file.id] = file.path
		ids = append(ids, file.id)
	}

	matchID, err := ResolveScopedIDIn(ids, scopeID, query, s.ExternalRefs())
	if err != nil {
		// Slug resolution missed. If the query is UID-shaped, fall back to an
		// exact-UID walk: the UID lives in frontmatter (not the path-derived
		// id), so it isn't in `ids`. ULIDs never collide with slugs, so this is
		// purely additive — it only runs when slug resolution already failed.
		if LooksLikeUID(query) {
			if f, ok, uidErr := s.findByUIDWithMode(files, query, mode); ok || uidErr != nil {
				return f, uidErr
			}
		}
		return nil, err
	}
	f, err := s.readPathWithMode(pathByID[matchID], matchID, mode)
	if err != nil {
		return nil, err
	}
	if info, err := os.Stat(pathByID[matchID]); err == nil {
		f.ModifiedAt = info.ModTime()
	}
	return f, nil
}

// findByUIDWithMode resolves a fiber by an exact (case-insensitive) UID match.
// The UID is frontmatter-only, so this walks the file list parsing metadata to
// read each UID; the caller gates it on LooksLikeUID so the scan only runs for
// UID-shaped queries that slug resolution already failed to resolve.
func (s *Storage) findByUIDWithMode(files []fiberFile, query string, mode ParseMode) (*Felt, bool, error) {
	for _, file := range files {
		meta, err := s.readPathWithMode(file.path, file.id, ParseMetadataOnly)
		if err != nil {
			continue
		}
		if !meta.MatchesUID(query) {
			continue
		}
		f, err := s.readPathWithMode(file.path, file.id, mode)
		if err != nil {
			return nil, true, err
		}
		if info, statErr := os.Stat(file.path); statErr == nil {
			f.ModifiedAt = info.ModTime()
		}
		return f, true, nil
	}
	return nil, false, nil
}

func (s *Storage) findExistingPathWithModeAndScope(scopeID, query string, mode ParseMode) (*Felt, bool, error) {
	query = cleanLookupQuery(query)
	if query == "" || !validLookupID(query) {
		return nil, false, nil
	}
	scopeID = cleanLookupScope(scopeID)
	if scopeID != "" && !validLookupID(scopeID) {
		return nil, false, nil
	}
	var candidates []string
	if strings.Contains(query, "/") {
		candidates = []string{query}
	}
	for _, scope := range scopeChain(scopeID) {
		candidates = append(candidates, scopedQuery(scope, query))
	}
	// A query spelled with this store's own prefix in the enclosing store's
	// namespace names a local fiber — but only once the query's own spelling
	// has come up empty, so a local id that really starts with the prefix
	// keeps its address. Hence: appended last, never substituted.
	if local, stripped := s.ExternalRefs().Localize(query); stripped {
		if strings.Contains(local, "/") {
			candidates = append(candidates, local)
		}
		for _, scope := range scopeChain(scopeID) {
			candidates = append(candidates, scopedQuery(scope, local))
		}
	}

	seen := make(map[string]struct{}, len(candidates))
	for _, candidate := range candidates {
		candidate = path.Clean(candidate)
		if _, ok := seen[candidate]; ok {
			continue
		}
		seen[candidate] = struct{}{}

		f, ok, err := s.readExistingPathWithMode(candidate, mode)
		if ok || err != nil {
			return f, ok, err
		}
	}
	return nil, false, nil
}

func validLookupID(id string) bool {
	return id != ".." && !strings.HasPrefix(id, "../") && !path.IsAbs(id)
}

func (s *Storage) readExistingPathWithMode(id string, mode ParseMode) (*Felt, bool, error) {
	filePath := s.Path(id)
	if !s.pathInStore(filePath) {
		return nil, false, nil
	}
	info, err := os.Stat(filePath)
	if os.IsNotExist(err) {
		return nil, false, nil
	}
	if err != nil {
		return nil, false, fmt.Errorf("checking file %s: %w", filePath, err)
	}
	if info.IsDir() {
		return nil, false, nil
	}

	f, err := s.readPathWithMode(filePath, id, mode)
	if err != nil {
		return nil, true, err
	}
	f.ModifiedAt = info.ModTime()
	return f, true, nil
}

func (s *Storage) pathInStore(filePath string) bool {
	root := filepath.Clean(s.root)
	filePath = filepath.Clean(filePath)
	rel, err := filepath.Rel(root, filePath)
	return err == nil && rel != "." && !strings.HasPrefix(rel, ".."+string(filepath.Separator)) && rel != ".."
}

func (s *Storage) listFiberFiles() ([]fiberFile, error) {
	// Resolve symlinks on the root so WalkDir descends into symlinked .felt/ dirs.
	rootResolved, err := filepath.EvalSymlinks(s.root)
	if err != nil {
		return nil, fmt.Errorf("resolving .felt path: %w", err)
	}
	var files []fiberFile
	visited := map[string]struct{}{}

	// walkFn walks one tier of the felt tree, recursing through any symlinked
	// subdirectory. `walkBase` is the absolute, symlinks-resolved root of this
	// tier; ids are computed relative to it so they stay clean even when the
	// symlink target lives outside `rootResolved` — the case where a
	// subdirectory of this store is a symlink into a foreign `.felt/`
	// elsewhere on disk (a "mounted" sub-store).
	//
	// `idPrefix` carries the symlink's logical position in the outer tree
	// (e.g. `projects/foo/`), and is prepended to inner-relative ids so
	// they surface in the outer namespace as `projects/foo/<inner>` instead
	// of leaking the resolved absolute path through filepath.Rel as
	// `../../<somewhere>/...`. The convention matches how regular
	// directories work: the path you place a symlink at *is* its name in
	// the outer namespace.
	var walkFn func(walkBase, idPrefix string) error
	// walkDirFn walks a single tier by hand (os.ReadDir + manual recursion)
	// rather than filepath.WalkDir, so it holds each directory's sibling
	// DirEntry list in memory. That list is what fs.WalkDir would have read
	// internally anyway; keeping it lets a fiber's `report.html` sibling be
	// detected by scanning entries already in hand — zero extra syscalls —
	// instead of an os.Stat per fiber.
	var walkDirFn func(dir, walkBaseResolved, idPrefix string) error
	walkDirFn = func(dir, walkBaseResolved, idPrefix string) error {
		entries, err := os.ReadDir(dir)
		if err != nil {
			return err
		}
		hasReportHTML := false
		for _, e := range entries {
			if !e.IsDir() && e.Name() == "report.html" {
				hasReportHTML = true
				break
			}
		}
		for _, d := range entries {
			fullPath := filepath.Join(dir, d.Name())
			// Symlinked subdirectory: capture its logical position relative to
			// walkBaseResolved before resolving, so the recursive walk lifts
			// every inner id back into the outer namespace.
			if d.Type()&os.ModeSymlink != 0 {
				target, err := filepath.EvalSymlinks(fullPath)
				if err != nil {
					continue // skip broken symlinks
				}
				info, err := os.Stat(target)
				if err != nil {
					continue
				}
				if info.IsDir() {
					inner, err := filepath.Rel(walkBaseResolved, fullPath)
					if err != nil {
						continue
					}
					nextPrefix := path.Join(idPrefix, filepath.ToSlash(inner))
					if err := walkFn(target, nextPrefix); err != nil {
						return err
					}
					continue
				}
				// Symlink to a regular file (e.g. a fiber .md symlinked in from
				// elsewhere): fall through to the normal file handling below —
				// filepath.WalkDir used to visit these too, since it doesn't
				// distinguish a symlink-to-file from a real file once resolved.
			}
			if d.IsDir() {
				if err := walkDirFn(fullPath, walkBaseResolved, idPrefix); err != nil {
					return err
				}
				continue
			}
			if !strings.HasSuffix(d.Name(), FileExt) {
				continue
			}
			// Compute rel within this tier (clean inner namespace), then prepend
			// the accumulated outer prefix to lift the id back into the parent
			// tree. Resolved-then-fullPath fallback preserves the prior
			// best-effort behaviour for pathological symlinks.
			resolved, err := filepath.EvalSymlinks(fullPath)
			if err != nil {
				resolved = fullPath
			}
			rel, err := filepath.Rel(walkBaseResolved, resolved)
			if err != nil {
				rel, err = filepath.Rel(walkBaseResolved, fullPath)
				if err != nil {
					return err
				}
			}
			id, entryPoint, ok := fiberIDFromRelativePath(rel)
			if !ok {
				continue
			}
			if idPrefix != "" {
				id = path.Join(idPrefix, id)
				// Crossing a symlink into a sub-store means this file is never
				// the *outer* entry-point fiber — the entry-point shape only
				// applies at the root the user is asking about.
				entryPoint = false
			}
			var reportPath string
			if hasReportHTML {
				reportPath = filepath.Join(dir, "report.html")
			}
			files = append(files, fiberFile{id: id, path: fullPath, entryPoint: entryPoint, reportPath: reportPath})
		}
		return nil
	}
	walkFn = func(walkBase, idPrefix string) error {
		walkBaseResolved, err := filepath.EvalSymlinks(walkBase)
		if err != nil {
			return nil // skip unresolvable roots
		}
		if _, seen := visited[walkBaseResolved]; seen {
			return nil
		}
		visited[walkBaseResolved] = struct{}{}
		return walkDirFn(walkBaseResolved, walkBaseResolved, idPrefix)
	}
	if err := walkFn(rootResolved, ""); err != nil {
		return nil, fmt.Errorf("walking .felt directory: %w", err)
	}
	return files, nil
}

// fiberIDFromRelativePath returns (id, entryPoint, ok). entryPoint is true
// when the file is a bare `<slug>.md` at the `.felt/` root — the shape the
// project-level root fiber takes.
func fiberIDFromRelativePath(rel string) (string, bool, bool) {
	rel = filepath.Clean(rel)
	dir := filepath.Dir(rel)
	base := strings.TrimSuffix(filepath.Base(rel), FileExt)
	if dir == "." {
		return base, true, true
	}
	if filepath.Base(dir) != base {
		return "", false, false
	}
	return filepath.ToSlash(dir), false, true
}

// ParentPath returns the parent fiber ID of id, or "" when id names a
// top-level fiber. Fiber IDs are clean, slash-separated and relative, so a
// rooted or empty input has no parent to speak of and degrades to "" rather
// than to "/" — the one answer no fiber ID can be.
func ParentPath(id string) string {
	clean := path.Clean(filepath.ToSlash(id))
	parent := path.Dir(clean)
	if parent == "." || parent == "/" {
		return ""
	}
	return parent
}

// ResolveAddPath disambiguates a new fiber's slug-path against the existing
// tree. When the leading segment of slug matches the basename of an existing
// fiber, the slug is rewritten so the new fiber lands under that fiber's
// parent — preventing silent top-level creation when the user meant to nest
// below a fiber that already lives deep in the tree.
//
// Resolution rules:
//   - Single-segment slugs (no `/`) are never resolved; top-level creation is
//     unambiguous in intent.
//   - If no existing fiber has a basename equal to the leading segment, the
//     slug is returned unchanged.
//   - If exactly one existing fiber matches, the new path is `<parent>/<slug>`,
//     and rewritten is true so the caller can inform the user.
//   - If the slug already corresponds to one of the candidate placements
//     (typically because the user passed a fully-qualified path), it's
//     returned as-is with rewritten=false — fully-qualified callers get no
//     surprise rewrite and no info chatter.
//   - If multiple candidates resolve to distinct paths, the function returns
//     an ambiguity error listing each candidate path; the caller must
//     fully-qualify the slug or opt into top-level placement.
func ResolveAddPath(slug string, existingIDs []string) (resolved string, rewritten bool, err error) {
	slug = path.Clean(strings.TrimSpace(slug))
	if !strings.Contains(slug, "/") {
		return slug, false, nil
	}
	leading := slug[:strings.Index(slug, "/")]

	// Candidate parents: each existing fiber whose basename matches the
	// leading segment contributes its parent directory. Parents are
	// deduplicated because two fibers can't share the same id, but two
	// fibers can share a basename in different subtrees.
	var candidates []string
	seenParents := map[string]struct{}{}
	for _, id := range existingIDs {
		if path.Base(id) != leading {
			continue
		}
		parent := ParentPath(id)
		if _, ok := seenParents[parent]; ok {
			continue
		}
		seenParents[parent] = struct{}{}
		var resolvedPath string
		if parent == "" {
			resolvedPath = slug
		} else {
			resolvedPath = parent + "/" + slug
		}
		candidates = append(candidates, resolvedPath)
	}

	if len(candidates) == 0 {
		return slug, false, nil
	}

	// If the user's input already matches one of the candidate placements
	// (e.g. they passed a fully-qualified path or top-level was the right
	// answer), use it as-is — no rewrite, no info chatter.
	if slices.Contains(candidates, slug) {
		return slug, false, nil
	}

	if len(candidates) == 1 {
		return candidates[0], true, nil
	}

	// Ambiguous: stable-sorted candidate list for a deterministic error.
	sort.Strings(candidates)
	return "", false, fmt.Errorf(
		"%q could resolve to multiple existing locations:\n  %s\npass a fully-qualified path or --top-level to disambiguate",
		slug,
		strings.Join(candidates, "\n  "),
	)
}

// ResolveScopedIDIn resolves query by walking up from scopeID like lexical
// scope, with knowledge of the enclosing store for callers that have a *Storage
// in hand (see Storage.ExternalRefs). A nil external is the top-level-store
// case.
func ResolveScopedIDIn(ids []string, scopeID, query string, external *ExternalRefs) (string, error) {
	return newScopedIDResolverIn(ids, external).Resolve(scopeID, query)
}

type scopedIDResolver struct {
	external     *ExternalRefs
	ids          []string
	exact        map[string]struct{}
	parentSorted map[string][]scopedIDEntry
	byBase       map[string][]string
}

type scopedIDEntry struct {
	base string
	id   string
}

func newScopedIDResolverIn(ids []string, external *ExternalRefs) *scopedIDResolver {
	resolver := &scopedIDResolver{
		external:     external,
		ids:          make([]string, 0, len(ids)),
		exact:        make(map[string]struct{}, len(ids)),
		parentSorted: map[string][]scopedIDEntry{},
		byBase:       map[string][]string{},
	}
	for _, id := range ids {
		cleanID := path.Clean(id)
		resolver.ids = append(resolver.ids, cleanID)
		resolver.exact[cleanID] = struct{}{}

		parent := ParentPath(cleanID)
		base := path.Base(cleanID)
		resolver.parentSorted[parent] = append(resolver.parentSorted[parent], scopedIDEntry{base: base, id: cleanID})
		resolver.byBase[base] = append(resolver.byBase[base], cleanID)
	}
	sort.Strings(resolver.ids)
	for parent, entries := range resolver.parentSorted {
		sort.Slice(entries, func(i, j int) bool {
			if entries[i].base != entries[j].base {
				return entries[i].base < entries[j].base
			}
			return entries[i].id < entries[j].id
		})
		resolver.parentSorted[parent] = entries
	}
	return resolver
}

func (r *scopedIDResolver) Resolve(scopeID, query string) (string, error) {
	query = cleanLookupQuery(query)
	scopeID = cleanLookupScope(scopeID)
	if query == "" {
		return "", fmt.Errorf("no felt found matching %q", query)
	}

	if id, ok, err := r.resolveInStore(scopeID, query); ok || err != nil {
		return id, err
	}

	// A target spelled from the enclosing store's namespace but pointing back
	// into this one (`ai-futures/felt/debug`) names a LOCAL fiber. It is tried
	// only after ordinary resolution has failed, so a local fiber whose id
	// genuinely begins with this store's own prefix still answers to its own
	// spelling — and a miss keeps the query the caller typed in its error.
	if local, stripped := r.external.Localize(query); stripped {
		if id, ok, _ := r.resolveInStore(scopeID, local); ok {
			return id, nil
		}
	}

	// Nothing in this store answers to the query. Before the basename rescue
	// below gets to guess, ask the enclosing store: a path that names a real
	// fiber THERE is not a stale local path, it is a link out of this view.
	//
	// The two rescues overlap, and this order resolves the overlap in the
	// enclosing store's favour. A stale local path whose slug is unique here
	// AND which the enclosing store INFERS — by its own suffix and basename
	// rules, over a far larger id set — is reported as external instead of
	// being repaired into the local fiber. The reader loses that repair, so
	// `felt check` reports it: an info issue naming both candidates, emitted
	// on the inferred branch only (see checkRelationshipIntegrity). The trade
	// is deliberate: a wrong redirect sends a reader one command away
	// (`felt -C ...`), while the misresolution it replaces silently answered
	// with the wrong fiber — and `felt rm` and `felt nest` act on that answer.
	if id, inferred, ok := r.externalHit(scopeID, query); ok {
		return "", r.external.err(query, id, inferred)
	}

	// Last resort: the query's final segment names exactly one fiber. This is
	// the rescue for a link whose PATH has gone stale — `felt nest` moves a
	// fiber and every wikilink written against the old path still points at the
	// right slug — and the store leans on it heavily (removing it turns some
	// five hundred healthy loom links into broken ones). It is also the step
	// that misreads a foreign path as a local slug, which is why an id known to
	// the enclosing store is refused above before ever reaching here.
	if ids := r.byBase[path.Base(query)]; len(ids) == 1 {
		return ids[0], nil
	}

	return "", fmt.Errorf("no felt found matching %q", query)
}

// externalHit asks the enclosing store about a query this store could not
// answer, in two steps of very different cost.
//
// The cheap step is a stat: does the query name a fiber at exactly that path
// out there? That is how a foreign id is normally written — it is what
// `felt ls` prints and what a user copies — so the common case costs two
// syscalls and always runs. Commands depend on it: it is what lets
// `felt rm ai-futures/portolan/debug` reach the fiber it names.
//
// The expensive step walks the enclosing store's whole id list, so that the
// slug and suffix rules that resolve `[[gotcha-…]]` from the loom resolve it
// from in here too. It runs on every local miss — ungated. It used to be
// gated on the basename fallback being about to fire, which made the answer
// depend on whether the query's slug happened to collide with a local one:
// `felt show portolan/debug` resolved or did not according to an accident of
// this store's naming. A partial foreign path now resolves either way, at the
// cost of one walk of the enclosing store's id list, memoized, only on a miss.
// It reports which of the two answered: an exact path stat is not inferred,
// the resolver walk is. Only the second can outrank a local rescue the reader
// was relying on, so only the second is worth remarking on (see check).
func (r *scopedIDResolver) externalHit(scopeID, query string) (id string, inferred, ok bool) {
	if r.external == nil {
		return "", false, false
	}
	if id, ok := r.external.LookupPath(query); ok {
		return id, false, true
	}
	id, ok = r.external.Lookup(scopeID, query)
	return id, ok, ok
}

// resolveInStore is resolution against this store alone: exact id, then the
// lexical scope chain, then the unique-suffix fallback. ok is false with a nil
// error when nothing matched; a non-nil error is a hard stop (ambiguity), not
// an invitation to try the fallbacks in resolve.
func (r *scopedIDResolver) resolveInStore(scopeID, query string) (string, bool, error) {
	if _, ok := r.exact[query]; ok {
		return query, true, nil
	}

	if strings.Contains(query, "/") {
		for _, scope := range scopeChain(scopeID) {
			candidate := scopedQuery(scope, query)
			// An exact id match wins over descendant prefix matches: resolving
			// [[a/parent]] must not be defeated into ambiguity by a/parent/child.
			if _, ok := r.exact[candidate]; ok {
				return candidate, true, nil
			}
			matches := r.prefixMatches(candidate)
			switch len(matches) {
			case 0:
				continue
			case 1:
				return matches[0], true, nil
			default:
				return "", false, fmt.Errorf("ambiguous ID %q in scope %q matches: %s", query, displayScope(scope), strings.Join(matches, ", "))
			}
		}
	} else {
		for _, scope := range scopeChain(scopeID) {
			matches := r.basenamePrefixMatches(scope, query)
			// Exact basename match takes priority over prefix matches: entries
			// are sorted by (base, id), so an exact base sorts strictly before
			// any entry that merely has query as a prefix.
			if len(matches) > 0 && path.Base(matches[0]) == query {
				return matches[0], true, nil
			}
			switch len(matches) {
			case 0:
				continue
			case 1:
				return matches[0], true, nil
			default:
				return "", false, fmt.Errorf("ambiguous ID %q in scope %q matches: %s", query, displayScope(scope), strings.Join(matches, ", "))
			}
		}
	}

	// Global fallback: when scope-relative resolution finds nothing, a query
	// that names the TAIL of exactly one id anywhere in the store resolves to
	// it. This lets a globally-unique slug be referenced from any scope
	// (including across projects) without a full path, and is scope-independent
	// so the same link resolves from the monorepo and a substore.
	if match, ok := r.uniqueSuffixMatch(query); ok {
		return match, true, nil
	}

	return "", false, nil
}

// uniqueSuffixMatch resolves a query naming the tail of exactly one id.
//
// The match must land on a SEGMENT boundary, and the whole query has to
// participate — which is the correction of the first cut, where the fallback
// took `path.Base(query)` and asked only whether that one word was unique.
// Everything before the last slash was discarded, so a link written out in
// full to a fiber in ANOTHER store — [[ai-futures/portolan/debug]] — quietly
// became a link to whatever local fiber happened to be called `debug`. In the
// felt project's own store that was the fiber doing the linking: it listed
// itself among its references, and `felt check` called it healthy.
//
// A path that fails here is a path with no home in this store, and saying so
// is the honest answer. The bare-slug case is unchanged: a one-segment query
// is its own tail.
func (r *scopedIDResolver) uniqueSuffixMatch(query string) (string, bool) {
	// Any id ending in `query` ends in its basename, so the basename bucket is
	// the candidate set — the loop only has to reject the near misses.
	suffix := "/" + query
	var match string
	found := 0
	for _, id := range r.byBase[path.Base(query)] {
		if id != query && !strings.HasSuffix(id, suffix) {
			continue
		}
		match = id
		found++
	}
	return match, found == 1
}

func (r *scopedIDResolver) prefixMatches(candidate string) []string {
	start := sort.SearchStrings(r.ids, candidate)
	var matches []string
	for _, id := range r.ids[start:] {
		if id != candidate && !strings.HasPrefix(id, candidate) {
			break
		}
		matches = append(matches, id)
	}
	return matches
}

func (r *scopedIDResolver) basenamePrefixMatches(scopeID, query string) []string {
	entries := r.parentSorted[scopeID]
	start := sort.Search(len(entries), func(i int) bool {
		return entries[i].base >= query
	})
	var matches []string
	for _, entry := range entries[start:] {
		if !strings.HasPrefix(entry.base, query) {
			break
		}
		matches = append(matches, entry.id)
	}
	return matches
}

func cleanLookupQuery(query string) string {
	query = strings.TrimSpace(query)
	if query == "" {
		return ""
	}
	query = path.Clean(query)
	if query == "." {
		return ""
	}
	return query
}

func cleanLookupScope(scopeID string) string {
	scopeID = strings.TrimSpace(scopeID)
	if scopeID == "" {
		return ""
	}
	scopeID = path.Clean(scopeID)
	if scopeID == "." {
		return ""
	}
	return scopeID
}

func scopeChain(scopeID string) []string {
	scopeID = cleanLookupScope(scopeID)
	if scopeID == "" {
		return []string{""}
	}
	var scopes []string
	for {
		scopes = append(scopes, scopeID)
		parent := ParentPath(scopeID)
		if parent == "" {
			break
		}
		scopeID = parent
	}
	return append(scopes, "")
}

func scopedQuery(scopeID, query string) string {
	if scopeID == "" {
		return query
	}
	return path.Join(scopeID, query)
}

func displayScope(scopeID string) string {
	if scopeID == "" {
		return "."
	}
	return scopeID
}

// FindProjectRoot walks up from the current directory to find a .felt directory.
func FindProjectRoot() (string, error) {
	dir, err := os.Getwd()
	if err != nil {
		return "", fmt.Errorf("getting working directory: %w", err)
	}

	for {
		feltDir := filepath.Join(dir, DirName)
		if info, err := os.Stat(feltDir); err == nil && info.IsDir() {
			return dir, nil
		}

		parent := filepath.Dir(dir)
		if parent == dir {
			// Reached filesystem root
			return "", fmt.Errorf("no .felt directory found")
		}
		dir = parent
	}
}

func readMetadataFile(path, id string) (*Felt, error) {
	frontmatter, err := readFrontmatterFile(path)
	if err != nil {
		return nil, err
	}
	return parseFrontmatter(id, frontmatter)
}

func readFrontmatterFile(path string) ([]byte, error) {
	data, err := os.ReadFile(path)
	if err != nil {
		return nil, err
	}
	frontmatter, _, err := splitFrontmatter(data, false)
	return frontmatter, err
}

func fileFrontmatterHasTopLevelFields(path string, fields []string) (bool, error) {
	frontmatter, err := readFrontmatterFile(path)
	if err != nil {
		return false, err
	}
	return frontmatterHasTopLevelFields(frontmatter, fields), nil
}

func frontmatterHasTopLevelFields(frontmatter []byte, fields []string) bool {
	if len(fields) == 0 {
		return true
	}

	remaining := make(map[string]struct{}, len(fields))
	for _, field := range fields {
		remaining[field] = struct{}{}
	}

	var node yaml.Node
	if err := yaml.Unmarshal(frontmatter, &node); err != nil || len(node.Content) == 0 {
		return false
	}
	mapping := node.Content[0]
	if mapping.Kind != yaml.MappingNode {
		return false
	}
	for i := 0; i+1 < len(mapping.Content); i += 2 {
		delete(remaining, mapping.Content[i].Value)
		if len(remaining) == 0 {
			return true
		}
	}
	return false
}

func (s *Storage) nextAvailableMigrationID(baseID string, reserved map[string]struct{}) (string, error) {
	for n := 1; ; n++ {
		candidate := baseID
		if n > 1 {
			candidate = fmt.Sprintf("%s-%d", baseID, n)
		}
		if _, ok := reserved[candidate]; ok {
			continue
		}
		if _, err := os.Stat(s.Path(candidate)); err == nil {
			continue
		} else if !os.IsNotExist(err) {
			return "", fmt.Errorf("checking id %s: %w", candidate, err)
		}
		return candidate, nil
	}
}

func remapIDPrefix(id, oldPrefix, newPrefix string) (string, bool) {
	id = path.Clean(id)
	oldPrefix = path.Clean(oldPrefix)
	newPrefix = path.Clean(newPrefix)
	if id == oldPrefix {
		return newPrefix, true
	}
	if strings.HasPrefix(id, oldPrefix+"/") {
		return newPrefix + strings.TrimPrefix(id, oldPrefix), true
	}
	return id, false
}
